### PR TITLE
LPS-104521 Add tests.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Cerrada, falla el semantic versioning, paso otra :)

**Comment by cgoncas** [comment]
ci:test:bundle

**Comment by cgoncas** [comment]
Reabierta, actualizado el branch con el SV

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80977. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/d243974339f9~3...d243974339f9)

**Pull request closed without merging**
