### PR TITLE
LPS-62989

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
Hey @adolfopa 

Could you please look at this and remove the references to com.liferay.registry in SearchResultManagerImpl.java?

**Comment by adolfopa** [comment]
@hhuijser @arboliveira  See https://github.com/arboliveira/liferay-portal/pull/95

**Comment by hhuijser** [comment]
@adolfopa 

I see you closed this pull.
What's the status on all this?

**Comment by adolfopa** [comment]
Sorry @hhuijser, I closed this by mistake while cleaning up my PR queue. @arboliveira Have you seen my pull request (see previous comment in this one)?

**Comment by arboliveira** [comment]
Reviewed https://github.com/arboliveira/liferay-portal/pull/95, submitted as https://github.com/brianchandotcom/liferay-portal/pull/38506.

**Pull request closed without merging**
