### PR TITLE
LPS-110135 Autogenerated

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86108. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/5114a69e9f27~1...5114a69e9f27)

**Pull request closed without merging**
