### PR TITLE
LPS-72729 Since AssetEntryException is not serializable, it could not be used with the @Test(expected) annotation, we could use this hack to assert that this exception is been thrown.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Al final descarte la otra opcion.

gracias por la ayuda 👍

**Comment by robertoDiaz** [comment]
@linolaoj 

We've been studied how to create a new mechanism more extensible  during this week because the curren one is really limitating. Finally, we've discarded it.

Sorry for the inconveniences.

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by linolaoj** [comment]
@robertoDiaz , thank you for all the work and dedication on this issue. :+1:

**Pull request closed without merging**
