### PR TITLE
LPS-107380 Fix test

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84074. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/3bc746627cc5~6...3bc746627cc5)

**Pull request closed without merging**
