### PR TITLE
LPS-68550 Add the compare version option in the render phase of each KB portlet

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc @sergiogonzalez

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
@adolfopa se me ha colado el primer commit "LPS-66495 Update tooltip texts", puedes quitarlo por favor?

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44264. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/724b245~1...724b245) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
