### PR TITLE
LPS-110656 add test to asset library role removal

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@austinchiang maybe check this one to make sure the failing tests were ignored/quarantined?

Needs a manual rebase before retesting

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Pull request closed without merging**
