### PR TITLE
[TS] LPS-120924 Use DLUtil to support UTF-8 characters as well

### PR DESCRIPTION
**Pull request by balazssk**
Hi @adolfopa ,

On MySQL the LENGTH function checks the byte size of the title column, not the character number. So titles with 2 or 3 byte characters (like Greek, Chinese) would not trigger this SQL
https://github.com/balazssk/liferay-portal/blob/6c9a96e7c0eb6ed027e6cfe073788b04dba39b3e/portal-impl/src/com/liferay/portal/upgrade/v7_0_0/UpgradeDocumentLibrary.java#L163 

Instead it would fall into https://github.com/balazssk/liferay-portal/blob/6c9a96e7c0eb6ed027e6cfe073788b04dba39b3e/portal-impl/src/com/liferay/portal/upgrade/v7_0_0/UpgradeDocumentLibrary.java#L548 where title.subString() could result in a StringIndexOutOfBoundsException.

Can you please review?
https://issues.liferay.com/browse/LPS-120924

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Added an SF commit for unchanged code

**Comment by balazssk** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
