### PR TITLE
LPS-103924 do not show current ddmStructure as additiona metadata field

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84609. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/542a56bdc398~2...542a56bdc398)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84624. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/cea93f044960~2...cea93f044960)

**Pull request closed without merging**
