### PR TITLE
LPS-65859 Add missing dummy step

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @sergiogonzalez

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/438. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/642d2a2~4...642d2a2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
