### PR TITLE
LPS-112548 Add depot to Task Assignment and Notitication

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1418.

**Comment by adolfopa** [comment]
@inacionery On top of your changes, everything works as expected. Thanks a lot!

**Comment by inacionery** [comment]
Awesome! Glad to help!

**Pull request closed without merging**
