### PR TITLE
[TECHNICAL-SUPPORT] LPS-88187

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @wanderlast

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@wanderlast @jonathanmccann I think this fix is wrong, main services shouldn't have to care about staging at all. They all should operate exclusively in the group the files belong to.

Additionally, isn't the issue a bit artificial? If the physical file is manually deleted from the store (either by mistake or purposefully) I'd expect this to fail. Also, nothing guarantees that the staging file hasn't been deleted as well in case of an accident, so this only covers the real problem in very specific cases.

Sorry!

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/765. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/c5783252c8df~1...c5783252c8df)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/jeyvison/liferay-portal/pull/888. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/c5783252c8df~1...c5783252c8df)

**Pull request closed without merging**
