### PR TITLE
Lps 86234 lima

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi @adolfopa 

PageComments and PageRatings are deployable portlets, and I believe their data handler needs to set a data level at portlet_instance rather than using the default level of SITE

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/388.

**Comment by adolfopa** [comment]
@arthurchan35 Can you send next PRs to the liferay-lima user? We're trying to concentrate all pull requests there.

Thanks!

**Comment by arthurchan35** [comment]
Hi @adolfopa 
Will do next time. I was aware of it before.

**Pull request closed without merging**
