### PR TITLE
LPS-54586 - Owner user cannot view their own newly uploaded Draft Documents

### PR DESCRIPTION
**Pull request by daviddotzhang**
see the email.

### CODE REVIEW

**Comment by daviddotzhang** [comment]
ci:reopen

**Comment by daviddotzhang** [comment]
ci:retest

**Comment by daviddotzhang** [comment]
see https://github.com/adolfopa/liferay-portal/pull/449,

I removed the last "SF" commit

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/443. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/2a1de004c7e4~6...2a1de004c7e4)

**Pull request closed without merging**
