### PR TITLE
[TS] LPS-109296 A redirect with status 301 happens wfor URLs with non-default locales

### PR DESCRIPTION
**Pull request by robertoDiaz**
https://issues.liferay.com/browse/LPS-109296

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
@NorbertKocsis This changes some core functionality. Can you write some tests to avoid regressions? Resend to me when finished.

Thanks!

**Comment by NorbertKocsis** [comment]
Hi,

What kind of tests do you have in mind?

Br,
Norbert

**Comment by adolfopa** [comment]
Write a regression test for the methods that call the private method you modified, and an integration test for the case described in the ticket.

**Pull request closed without merging**
