### PR TITLE
LPS-65434 Fix an issue when overriding MVCCommands and also consider service.ranking

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by sergiogonzalez** [comment]
ci:retest

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/39253. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
