### PR TITLE
LPS-107018 | No friendly url generated for web content when two locales share same title

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @adolfopa, 

This pr comes from https://github.com/ealonso/liferay-portal/pull/2795. 

Besides [LPS-107018](https://issues.liferay.com/browse/LPS-107018), there's further information about this issue in [PTR-1438](https://issues.liferay.com/browse/PTR-1438). 

The solution takes into account two factors when creating a `urlTitleMap` for a new or an existing web content: 

1. One is whether another web content is already using the friendly url created from the title.
2. The second is whether two localizations for the same web content will end up having the same friendly url. 

The first factor is taken care of by `JournalArticleLocalServiceImpl._getURLTitleMap`.

The second factor, namely getting unique titles for different locales, is not covered by this method for new web contents because nothing has been persisted to the database at that point, so checking for unique url titles never fails. The second factor is actually taken care of by `FriendlyURLEntryLocalServiceImpl._getUniqueUrlTitle`. 

The logic for updating friendly url entry localizations is also corrected. 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
I'll wait until next week due to GA2 release.

**Comment by adolfopa** [comment]
@ricardocousolr Can you write some tests? The service logic is pretty tricky ...

**Comment by adolfopa** [comment]
@ricardocousolr is working on the tests. Closing this in the meanwhile.

**Comment by ricardocousolr** [comment]
Added tests to new pr but also an upgrade step to add missing friendly url entry localizations. Sending first to @robertoDiaz. (https://github.com/robertoDiaz/liferay-portal/pull/825)

**Pull request closed without merging**
