### PR TITLE
LPS-81812 change message in body if message is updated.

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia We shouldn't embed untranslated english text within the code.  Instead fo this, we should create a specific template for the "update" case, as is done in Journal.

**Comment by AliciaGarciaGarcia** [comment]
replaced by https://github.com/adolfopa/liferay-portal/pull/1070

**Pull request closed without merging**
