### PR TITLE
LPS-74547 "Add subfolder" function in the DMS-Portlet renames the root folder

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey @sergiogonzalez 

If you are reviewing the LPS, could you please also take a look on this pull?

Thank you in advance,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
@IstvanD I can still reproduce the problem with these changes? Can you verify that these are correct?

Thanks!

**Comment by IstvanD** [comment]
Hey @adolfopa 

You mean, that 

- if you made a folder the root folder of a DM portlet,
- placed a file into that folder,
- moved the file to another folder,
- and on the way you have chosen to put it in a newly created subfolder

then instead of creating a new subfolder to the root and placing the file there, it ended up renaming the root folder?

Thank you!
István

**Comment by IstvanD** [comment]
Hey @adolfopa 

I forgot to mention that on master/DXP when you move a document, you can only create a subfolder to the Home (default) folder, but not the folder the file is currently residing.
In the "move entries" dialog (move_entries.jsp), the New Folder field will have always have the Home folder selected by default.
If I click on the Select button, this value (Home) will be transferred to the Select Folder dialog (select_folder.jsp) and you can add subfolders only under that folder.

I'm not sure if this is a bug or not.

Best regards,
István

**Comment by IstvanD** [comment]
Hey @adolfopa 

Did you get the same results by following the steps above?

I think the behavior outlined in my last comment should be dealt as a separate issue if it turns out to be a bug.

Thank you,
István

**Pull request closed without merging**
