### PR TITLE
LPS-66976 Update build scripts to use the last version of the module

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/1. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/2840a00~8...2840a00) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
