### PR TITLE
[TS] LPS-103174 Catch exception in case adaptive media doesn't exists and write a WARN trace

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79546. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/98a1e8e7ec90~1...98a1e8e7ec90)

**Pull request closed without merging**
