### PR TITLE
[TECHNICAL-SUPPORT] LPS-89319

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @Alec-Shay

Notes from Alec:

> Relevant tickets:
> 
> https://issues.liferay.com/browse/LPP-32725
> https://issues.liferay.com/browse/LPS-89319
> 
> Also, very similar issue: https://issues.liferay.com/browse/LPS-88516
> 
> This is a race condition in which the upgrade for Blogs may occur before the portal is initialized, which causes the upgrade to fail. Unfortunately due to the nature of the issue it is not easily testable. Please let me know if there are any questions or concerns about this. Thanks.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/67054

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/860.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/862. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/0a5355e005b6~1...0a5355e005b6)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/990. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/d0df81019907~1...d0df81019907)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/1021. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/79486dc41226~1...79486dc41226)

**Pull request closed without merging**
