### PR TITLE
[TECHNICAL-SUPPORT] LPS-92667

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @SpencerWoo

> https://issues.liferay.com/browse/LPS-92667
>
> https://issues.liferay.com/browse/LPS-90245 added support to search asset entry by class ids. Here we add support to counting asset entry by class id.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @SamZiemer 

Everything related to Asset and Journal should be sent to @ealonso.  Can you forward the PR to him?

Thanks!

**Comment by SamZiemer** [comment]
Thanks @adolfopa forwarded here: https://github.com/ealonso/liferay-portal/pull/2287

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/897. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/1b5f6b2e9caa~3...1b5f6b2e9caa)

**Pull request closed without merging**
