### PR TITLE
LPS-97699 When file is created via drag and drop, Guest user should not have default permissions assigned when layout is not public

### PR DESCRIPTION
**Pull request by IstvanD**
Dear @adolfopa 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear @adolfopa 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
As I see, the failed tests are not related to the changes.

**Comment by adolfopa** [comment]
Hey @IstvanD 

Sorry for the delay.  I need to attend to other things, but I'll review this first thing tomorrow morning.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75470

**Pull request closed without merging**
