### PR TITLE
LPS-71635 second part of the contribution

### PR DESCRIPTION
**Pull request by mmariuzzo**
Hi Adolfo, according to @sergiogonzales I'm sending you a pull request with the  second part of my contribution about the introduction of some extensions to DML to improve the integration with online tools.
This part is related to DocumentConversionUtil and the strict use of OpenOffice to convert doc, xls and other office formats to pdf and then to thumbnal and preview images.
OpenOffice is use also to export JournalArticle and Wiki, or to comapre versione.
The idea is to transform it in a framework to be able to use a different tool and manage formats not supported by OpenOffice.

I've tried different approaches but haven't found a good way to consume OSGi services from portal-impl.
So I've followed AuditRouter or LockManager approach:
- have interface and util in portal-kernel and use a ServiceProxy to consume a bundle service
- have an API bundle with a single service implementation (the manager)
- in the same bundle I'm declaring the ConverterWrapper interface
- in another bundle we have OpenOfficeConverterWrapper that is the actual OpenOffice code but used as a service
- developers can implement ConverterWrapper for example to manage MSProjects or CAD files

I've updated some build.gradle to use portal-impl:default and portal-kernel:default. 
Maybe you will to revert to the right next specific version

### CODE REVIEW

**Comment by adolfopa** [comment]
Sorry for the delay @mmariuzzo 

I couldn't take a look at this yet (I was on vacation last week), but I'll check it out as soon as possible.

Thanks!

**Comment by mmariuzzo** [comment]
Ok. I'm available for every doubts

**Comment by mmariuzzo** [comment]
Hi @adolfopa, I've noted some of my code conflicts with LPS-71382 commited by Pei-Jung Lan.

IMHO the problem is you are still focused on having a single DocumentConverter, in you scenario OpenOffice.

My proposal is to allow multiple converters because ones is able to convert "html to pdf", another is able to convert "dwg to pdf", another is able to convert "only MS formats to pdf" better then OpenOffice.

Ok, I will analyze better the new code to provide a contribution base on it. 
The idea is to transform the actual DocumentConvertionImpl in a dispatcher to the right converter tool.

**Comment by mmariuzzo** [comment]
I've reworked the code and created a new pull-request #539

**Pull request closed without merging**
