### PR TITLE
[TS] LPS-104076 Avoid NPE in case there is no DL

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-104076

Regression caused by LPS-91884, in case you remove DL processor in portal-ext.properties (dl.file.entry.processors property) a NPE is thrown during *DLPreviewRendererProviderFactory activation

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80448.

**Pull request closed without merging**
