### PR TITLE
LPS-96880 FriendlyURLLocalization is not being imported when companyId is not default

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
Hi @adolfopa, 

Just wanted to know if you had had the chance to look at this pr.

Thanks!

**Comment by adolfopa** [comment]
Yes, I sent a PM to @jgarcialr about it.

The thing is that I don't see why is it necessary to do the extra check (`friendlyURLEntry.getCompanyId() != portletDataContext.getSourceCompanyId()`). At first glance, it doesn't make sense for the company IDs to be different; it looks like there's a bug in a different place and we're working around it here.

Do you have more details on this?

Thanks!

**Comment by ricardocousolr** [comment]
Hi @adolfopa,

Sorry, I wasn't aware of you message to @jgarcialr  (he's out of office this week). I'll have a look at the code to see if I can come up with something useful. Otherwise, we'll have Jorge take a look.

Thanks!

**Comment by ricardocousolr** [comment]
Hi @adolfopa,

I haven't made much progress on this other than the naive comment that `friendlyURLEntry.getCompanyId()` might give back the _target_ company id, so it could be worth checking in case export/import is being done between different companies. In any case, I'll hand this back to @jgarcialr.

**Comment by adolfopa** [comment]
@jgarcialr will send another pull after further investigation.

Thanks!

**Pull request closed without merging**
