### PR TITLE
LPS-108722 buildLang

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85258. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/193acdaa0158~6...193acdaa0158)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85308. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/87b9fc78d39e~7...87b9fc78d39e)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85327. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/b1e6349762c2~8...b1e6349762c2)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85395. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/b645fe2402b6~8...b645fe2402b6)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85420. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/627848cf9e8a~8...627848cf9e8a)

**Pull request closed without merging**
