### PR TITLE
[TECHNICAL-SUPPORT] LPS-100082

### PR DESCRIPTION
**Pull request by jonathanmccann**
@adolfopa,

The new changes are the following:

https://github.com/adolfopa/liferay-portal/pull/1096/commits/85b717c8e1cb8c33209d756191ca67d1e9a41b37 - The existing APIs did not consider whether or not a notification was delivered and this resolves that. For instance, when choose "Mark all notifications as read" it would archive all notifications whether or not they had been delivered yet. I had to use `getDeliveredArchivedUserNotificationEventsCount` as a method name because the method signature conflicted with another one with the name of `getArchivedUserNotificationEventsCount`. Feel free to rename this as you see fit.

https://github.com/adolfopa/liferay-portal/pull/1096/commits/55c3af9f25a8f1e63923ad15d4cb67d63e6e7002 - As part of the renaming in the service.xml these calls also need to be updated (A -> AR)

https://github.com/adolfopa/liferay-portal/pull/1096/commits/3d1a4a91c7c5ed2bac9b4572e55604bba57adbba - The deprecations were asked for by Brian but I'm not entirely sure if these are the right ones or if I'm missing any. Feel free to amend this commit if there is something missing.

If you have any questions or concerns please let me know.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79112.

**Pull request closed without merging**
