### PR TITLE
LPS-112464 Clay 3.x IconTag, BadgeTag, LabelTag and StickerTag

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @adolfopa, this PR is an initial attempt at rewriting the legacy soy-based Clay Tags into pure Java + JSP? + React tags for better performance.

This PR contains:

### `clay:icon`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation

### `clay:badge`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation
- Replacement of raw html usages. This should be fine performance-wise now... 🤞 

### `clay:label`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation
- Replacement of raw html usages. This should be fine performance-wise now... 🤞 

### `clay:sticker`
- Tag migration
- Legacy tag attribute deprecation 
- Legacy tag implementation deprecation
- Replacement of raw html usages. This should be fine performance-wise now... 🤞 

Could you please take a look, specially at the Java part?

Thanks!

/cc @wincent

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Screen Shot 2020-05-26 at 09 19 52

**Comment by jbalsas** [comment]
believeinyourdreams

**Comment by adolfopa** [comment]
ci:help

**Comment by adolfopa** [comment]
ci:test:accounts

**Comment by adolfopa** [comment]
ci:test:documents

**Comment by adolfopa** [comment]
ci:test:echo

**Comment by jbalsas** [comment]
All those tests...

gottahavefaith

**Comment by jbalsas** [comment]
@adolfopa, estás contento?

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
