### PR TITLE
LPS-107732 remove UploadItemSelector for Blogs

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83964. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/16aae1cb3cff~4...16aae1cb3cff)

**Pull request closed without merging**
