### PR TITLE
LPS-89948 - Added DynamicCapability to portlet repository

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa  check with @4lejandrito if this has some reason to not have the DinamicCapability on the portlet

**Comment by adolfopa** [comment]
Waiting for https://issues.liferay.com/browse/LPS-97276 to get merged.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74921

**Pull request closed without merging**
