### PR TITLE
LPS-85933 Rename variable

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
See https://github.com/adolfopa/liferay-portal/pull/741. 
Please @julien, could you delete this PR?

**Comment by adolfopa** [comment]
Closing in favor of https://github.com/adolfopa/liferay-portal/pull/741

**Pull request closed without merging**
