### PR TITLE
LPS-69240 Reorder

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc @4lejandrito

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
@adolfopa Can you please check why this PR failed?

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/16. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/f576890~2...f576890) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
