### PR TITLE
[TS] LPS-110418

### PR DESCRIPTION
**Pull request by ChrisKian**
From @kevhlee:

> <https://issues.liferay.com/browse/LPS-110418>
> 
> The issue was that the notification portlet tried to invoke a method on the `userNotificationFeedEntry` variable when it was set to `null`.
> 
> * <https://github.com/kevhlee/liferay-portal/blob/4c6f47997f515e43e4ee78f52b5a64df6d9fdcec/modules/apps/notifications/notifications-web/src/main/resources/META-INF/resources/notifications/user_notification_entry.jspf#L55>
> 
> When a notification comes from a module that is uninstalled or deactivated, its corresponding `userNotificationFeedEntry` variable is set to `null`, which causes the problem described in [LPS-110418](https://issues.liferay.com/browse/LPS-110418).
> 
> With regards,
> Kevin

There was also some incorrect logic in the jspf file, as the "when" clause was assumed to be working as a "switch" clause, which isn't the case.  I've updated the logic and confirmed with Kevin the changes work as intended.  Please let me know if you have any questions, thanks!

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86533.

**Pull request closed without merging**
