### PR TITLE
[TS] LPS-87555 DLFileEntry results are not retrieved when using searchContext.setIncludeAttachments(true)

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-87555](https://issues.liferay.com/browse/LPS-87555)

Hi Adolfo,

Please review my pull request.

If you have any questions or concerns, please do not hesitate to contact me.

Thank you in advance,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:search

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/73384

**Pull request closed without merging**
