### PR TITLE
LPS-92284

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-92284

From @jrao:

> Don't show View in Context link for blog entries with no suitable context (i.e., don't display View in Context links that would result in a 404)

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @jrao @ChrisKian 

I'll put this on hold for a couple of days. There's nothing wrong with this change, but before merging I would like to extract the common parts this shares with D&M to avoid duplication. The thing is that we're so close to the UI freeze that we need to prioritize other tasks over this. I'll push this forward  first this next week.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/70798

**Pull request closed without merging**
