### PR TITLE
[TS] LPS-89922

### PR DESCRIPTION
**Pull request by brianikim**
Resending from https://github.com/adolfopa/liferay-portal/pull/824

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
The test failures do not seem related, but I will re-run to make sure.

**Comment by brianikim** [comment]
ci:retest

**Comment by adolfopa** [comment]
Hey @brianikim 

There are a couple of auto SF issues. Could you take a look at them?

Also, it seems the new finder method you created uses inline permissions. Why filter them again with `filterFileEntryTypes`? Shouldn't the inline permissions take care of permissions?

Thanks!

**Comment by brianikim** [comment]
ci:test:SF

**Comment by brianikim** [comment]
Hello @adolfopa ,

Thank you for pointing out the redundancy. I am currently resolving it and will be resending the PR soon. As for the Auto SF issues, can you point out the specific issues you are seeing? According to the test results of ci:test, it looks like the source formatter ran successfully.

**Comment by adolfopa** [comment]
Thanks @brianikim !

The Auto SF was complaining about some unused query id in the Finder/custom-sql.xml. I don't have the error output handy, but running ant format-source from portal-impl should get you the results.

**Pull request closed without merging**
