### PR TITLE
LPS-128855 Access Asset Entry in Blogs Widget Template without serviceLocator

### PR DESCRIPTION
**Pull request by epgarcia**
@sammonsjl This introduces an alternative to serviceLocator to obtain the blog asset entry.

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:stable

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
