### PR TITLE
LPS-108740 Add tests.

### PR DESCRIPTION
**Pull request by cgoncas**
/cc @drewbrokke

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85169. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/61709f2786d9~1...61709f2786d9)

**Pull request closed without merging**
