### PR TITLE
LPS-107160 Blogs cover image: large images added through the Item Selector

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
@adolfopa I have rebased this branch with master... please update yours

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84323. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/451e5d51ec1d~2...451e5d51ec1d)

**Pull request closed without merging**
