### PR TITLE
LPS-110134

### PR DESCRIPTION
**Pull request by ChrisKian**
From @jesseyeh-liferay:

> [LPS-110134](https://issues.liferay.com/browse/LPS-110134)
> 
> This handles an edge case from the solution introduced by [LPS-107966](https://issues.liferay.com/browse/LPS-107966), which propagates the image description when creating a new image via an image edit in Web Content.
> 
> image
> 
> After the first edited image is created, creating another image from this image edit results in the new image having a description of "undefined." To resolve this, we use the `fileEntryId` field introduced by [LPS-108098](https://issues.liferay.com/browse/LPS-108098), since this field gets propagated to edits of image edits (see [`editedItem` in `handleSaveEdit`](https://github.com/wanderlast/liferay-portal/blob/0b53476f588a4afbd7e22fc074a97d558d902967/modules/apps/item-selector/item-selector-taglib/src/main/resources/META-INF/resources/item_selector_preview/js/ItemSelectorPreview.es.js#L217)) and can be used to obtain the image description. Additionally, we remove the old `description` field and its references to eliminate redundancy.

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1350. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/19ea25483b24~2...19ea25483b24)

**Pull request closed without merging**
