### PR TITLE
Lps 109525 added commits

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @adolfopa,

This is additional commits for LPS-109525 to fix an issue where the classNameId is changed after upgrading the subscription classNameIds. I spoke with @achaparro regarding this and we think this is the best option, allow implementing classes to choose if we want to delete duplicates.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:stop

**Comment by SamZiemer** [comment]
ci:close

**Comment by michaelhashimoto** [comment]
Your pull request test has been aborted. We are sorry of the inconvenience but QA is in the process of refining the `ci:test:relevant` test suite. Unfortunately this particular pull request test has exceeded the maximum resource limit and will be aborted. Please contact your team's QA representative(s) for next steps. If your team does not have one then please make a post in [#d-quality-assurance](https://liferay.slack.com/archives/CL84ZPHAT)

**Pull request closed without merging**
