### PR TITLE
Lps 102610 katie

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @katienesterovich 

Notes from Katie:
> https://issues.liferay.com/browse/LPS-102610
> 
> `NoSuchLayoutException` triggers a Clay toast alert which is not suppressed. As a fix, I created a check to prevent error pop-ups due to `NoSuchLayoutException`.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/ealonso/liferay-portal/pull/2588.

**Pull request closed without merging**
