### PR TITLE
LPS-55103 Breaking changes

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/robertoDiaz/liferay-portal/pull/228. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/aafa8a9~3...aafa8a9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
