### PR TITLE
LPS-111890 Increase version range

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Semver should be fixed by 12cbd0f

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Looks like other pull requests in the past two hours have been passing so the Semver issue should be gone now (I think CI had issues yesterday).

Display Pages test failures are fixed in https://issues.liferay.com/browse/LPS-113059

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/36

**Pull request closed without merging**
