### PR TITLE
LPS-110068 avoid asset libraries duplication on list

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86310. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ac578a26b8e7~1...ac578a26b8e7)

**Pull request closed without merging**
