### PR TITLE
[TECHNICAL-SUPPORT] LPS-104144

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-104144

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test:sf

**Comment by JosemariaMunoz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80614.

**Pull request closed without merging**
