### PR TITLE
[TS] LPS-108915

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-108915

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/ChrisKian/liferay-portal/pull/185. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/1e544ae8c990~3...1e544ae8c990)

**Comment by adolfopa** [comment]
See https://github.com/ChrisKian/liferay-portal/pull/185

**Pull request closed without merging**
