### PR TITLE
Fix test failure.

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by Preston-Crary** [comment]
Hey @adolfopa,

if there's too many methods that need to be wrapped to cover everything you should be able to move the required logic into AdvancedPermissionChecker (might need to inline a couple String constants for the role names).  If it's too Depot specific, I'll make an extension point and move your code into it.

**Comment by adolfopa** [comment]
@Preston-Crary I'll try to look into this asap, but right now we need to concentrate on test stabilization. I'll send you a pr in the next couple of days.

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1351.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1353. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/3c8291a0a0ab~1...3c8291a0a0ab)

**Pull request closed without merging**
