### PR TITLE
LPS-89922

### PR DESCRIPTION
**Pull request by brianikim**
Resending from #847

Please make sure your master is updated to a hash that has: https://github.com/brianchandotcom/liferay-portal/pull/68475 before you test any local format-source errors (make sure you use ant format-source-all over ant format-source-current-branch. current-branch command throws out the false errors that were fixed in https://github.com/brianchandotcom/liferay-portal/pull/68475).

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @adolfopa ,

Latest ci:test is looking good.

Sincerely,
Brian Kim

**Comment by adolfopa** [comment]
Hey @brianikim 

Apologies if I missed some comment in one the previous PRs, but I still don't understand why do we need to do further filtering on the document types. The inline permission helper should take care of that.

**Pull request closed without merging**
