### PR TITLE
LPS-97294 Add callback to update field

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @katienesterovich

Notes from Katie:
> https://issues.liferay.com/browse/LPS-97294
> 
> Although state.value was updated to ' ', the field retained the original value. To fix, I added a callback to update field in addition to setting the value to ' '.
> 
> Note: see "Fixed" video attached in JIRA to see results.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/104.

**Pull request closed without merging**
