### PR TITLE
[TS] LPS-108098

### PR DESCRIPTION
**Pull request by ChrisKian**
From @jesseyeh-liferay:

> [LPS-108098](https://issues.liferay.com/browse/LPS-108098)
> 
> ## Previous Pull Requests
> 
> https://github.com/wanderlast/liferay-portal/pull/43 > https://github.com/ChrisKian/liferay-portal/pull/187 > https://github.com/adolfopa/liferay-portal/pull/1300
> 
> ## Changelog
> 
> This introduces an alternative solution to propagate Custom Fields that avoids JSON serialization. Instead, the `fileEntryId` from the original image is forwarded, which the upload request uses to retrieve the `FileEntry`, from which it then obtains the original Custom Fields.
> 
> ## Additional Notes
> 
> An edge case for this solution occurs if the original `FileEntry` is deleted before the upload request is completed. This raises a `NoSuchFileEntryException`, which is handled [here](https://github.com/wanderlast/liferay-portal/blob/e5325fadead2b204b5e5407a6667531a203c5710/modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/upload/DLUploadFileEntryHandler.java#L88-L100). Logic then proceeds normally and a new `FileEntry` is added (sans Custom Fields).

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86588. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/d5221f9adfc6~1...d5221f9adfc6)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86590. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/81910f7273f4~1...81910f7273f4)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1342. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/b37da3baf030~1...b37da3baf030)

**Pull request closed without merging**
