### PR TITLE
[TECHNICAL SUPPORT] LPS-66452 Mentions can't handle all valid characters in screenNames

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi,

Sorry, the LPS wasn't in progress, but I already have a solution just had to test it on master too.
So I guessed I could send you the pull :)

https://issues.liferay.com/browse/LPS-66452

Br,
Norbert

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
@NorbertKocsis This PR is on hold, as we're gonna make some changes that will affect the mention matching/recognition logic. Meanwhile, I'll keep this open so that we don't forget about it.

Thanks!

**Comment by NorbertKocsis** [comment]
Ok.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/44008

**Comment by adolfopa** [comment]
The previous PR autoclosed. See https://github.com/brianchandotcom/liferay-portal/pull/44040

**Pull request closed without merging**
