### PR TITLE
LPS-104259 LPS-107401 

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by yxingwu** [comment]
ci:retest:relevant

**Comment by yxingwu** [comment]
ci:retest:relevant

**Comment by yxingwu** [comment]
Hi @adolfopa 
I run test on the PR to myself [https://github.com/yxingwu/liferay-portal/pull/150](https://github.com/yxingwu/liferay-portal/pull/150). It seems ok.

**Comment by yxingwu** [comment]
ci:retest:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Hey @yxingwu 

Just wanted to let you know that I'm still looking into this. I need to test the CMIS connector throroughly to see if we need to update the OpenCMIS version as well.

**Comment by adolfopa** [comment]
@yxingwu We need to update the whole set of libraries that depend on CXF to avoid any problems. We have to keep the library versions consistent.

**Comment by yxingwu** [comment]
Hi @adolfopa ,
I found the latest version of OpenCMIS is 1.1.0 and it has a dependency on CXF(the version is 3.0.12). But the 3.0.12 version of CXF also has the security bug. To avoid the security bug, we must use the 3.3.4 version of CXF  or later. That means we can't really keep the library versions consistent.

**Comment by adolfopa** [comment]
Pinging you in private.

**Pull request closed without merging**
