### PR TITLE
Lps 110250

### PR DESCRIPTION
**Pull request by balazssk**
Hi @adolfopa ,
I've made this addition to https://issues.liferay.com/browse/LPS-106891 so that Admins can set Google Analytics' "Create Only Fields" https://web.archive.org/web/20200301065821/https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference , original Google dev site returns service unavailable, hence the web.archive.org link.

Can you please review?
https://issues.liferay.com/browse/LPS-110250

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86225.

**Pull request closed without merging**
