### PR TITLE
LPS-111938 Update to metadata-extractor 2.13.0

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
@john-co please look into this error, also in https://github.com/4lejandrito/liferay-portal/pull/475#issuecomment-618417077. Network? CI? GitHub? Something else?
```
     [exec] A problem occurred evaluating project ':util:sass-compiler-jni'.
     [exec] > Can't get https://github.com/liferay/clay/archive/v2.14.2.zip to /root/.liferay/mirrors/github.com/liferay/clay/archive/v2.14.2.zip.tmp
     [exec] 
```

**Comment by john-co** [comment]
@jpince, Looks like it could be network, ci, github related. @pyoo47 or @michaelhashimoto can you confirm?

**Pull request closed without merging**
