### PR TITLE
LPS-105119 Use item selector to select web contents in DDM.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/284. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/f426975049b7~1...f426975049b7)

**Pull request closed without merging**
