### PR TITLE
LPS-86850 Semver

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/robertoDiaz/liferay-portal/pull/745

**Comment by adolfopa** [comment]
Sorry, closed this by mistake.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/64954

**Pull request closed without merging**
