### PR TITLE
LPS-100969 extract get title method to manager

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/AliciaGarciaGarcia/liferay-portal/pull/22. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/7228ebaed064~2...7228ebaed064)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/92. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/7228ebaed064~2...7228ebaed064)

**Pull request closed without merging**
