### PR TITLE
LPS-106556 baseLine

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84137. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/8313c6213a72~1...8313c6213a72)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84159. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/49fc8f4c7970~1...49fc8f4c7970)

**Pull request closed without merging**
