### PR TITLE
[TS] LPS-88004 Staging should not restrict deleting or editing comments on Live site when required permissions are granted

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-88004

Hey Adolfo,

Vendel checked all entities (including the private modules) supporting discussion (based on their `resource-actions` xml and found these "affected":
* BlogsEntry
* DLFileEntry
* JournalArticle
* Layout
* WikiPage

Not affected:
* CalendarBooking uses a different approach for checking comment permissions in staging. It is working correctly already.
* TaskEntry is not staged at all, so there's no need to control permissions from staging perspective.

Author: @vendeltoreki
Reviewers: @danielkocsis, @lipusz
Staging review: :heavy_check_mark: 
Security review: :heavy_check_mark: 

@ealonso: fyi since it changes `JournalArticleModelResourcePermissionRegistrar`. Just in case you want to take a look at.

Thanks,
Tibor

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/vendeltoreki/liferay-portal/pull/5

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78239. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/2527d0b1b3c2~9...2527d0b1b3c2)

**Pull request closed without merging**
