### PR TITLE
LPS-107620 Check the width and height of the images and do not process them if they are too big.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84325. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/8a1655c58d34~4...8a1655c58d34)

**Pull request closed without merging**
