### PR TITLE
[TECHNICAL-SUPPORT] LPS-98770

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @knchau

> https://issues.liferay.com/browse/LPS-98770
> 
> The issue is that the Asset Publisher displays the author's name of an anonymous message board post. 
> 
> If the asset is a type "message", it'll check if the message post is anonymous and sets it to a field to be used to determine whether the author should be displayed.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
Hi @SamZiemer,

I have reviewed your changes and gone for a slightly different solution (See https://github.com/ealonso/liferay-portal/pull/2487).

The problem with your solution is that couples asset publisher (a generic component) with message boards (a specific one). Asset publisher should know nothing about specfic assets. They should all be abstracted through the AssetRenderer interface.

Does it make sense?

Please let me know if you have any questions.

**Comment by 4lejandrito** [comment]
See https://github.com/ealonso/liferay-portal/pull/2487.

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
