### PR TITLE
LPS-86455

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi @robertoDiaz,

Thanks for looking at this issue. I've verified that this fix also works for images and audio files. The only changes I have made is to rebase it to latest master and to run source formatter. Please let me know if there's anything else I can do for you to help with the testing of this issue. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
Hi @adolfopa,
Do you happen to have an ETA for when you'd be able to take a look at this? Thanks!

@robertoDiaz, there appears to be rebase errors now. Would you like me to rebase and resend this pull or do you want to handle it yourself? Thanks!

**Comment by adolfopa** [comment]
@wanderlast I'll try to get this reviewed this monday. About the rebase errors, I'll handle them, no worries.

**Comment by wanderlast** [comment]
Thanks for the update @adolfopa!

**Comment by adolfopa** [comment]
See https://github.com/wanderlast/liferay-portal/pull/23

**Pull request closed without merging**
