### PR TITLE
LPS-106703 test creation of layout with custom tags

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:seo

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83861. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/bb8a9308e992~6...bb8a9308e992)

**Pull request closed without merging**
