### PR TITLE
LPS-104259

### PR DESCRIPTION
**Pull request by yxingwu**

### CODE REVIEW

**Comment by yxingwu** [comment]
ci:test:sf

**Comment by yxingwu** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@yxingwu Can you split this pr in two? The 'portal-remote-*' pieces should be sent to @csierra; the repository one to me. We need to test each of these separately to minimize the risk of regressions.

Thanks!

**Pull request closed without merging**
