### PR TITLE
LPS-72803 Move constants to a class [layout]

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49573

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/590. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/f5683c2febb5~6...f5683c2febb5)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/598. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/12bd3677c248~8...12bd3677c248)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/601. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ed7f7e875d9c~9...ed7f7e875d9c)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/605. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/30b66a9046e2~9...30b66a9046e2)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/606. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/950a91f5efc7~9...950a91f5efc7)

**Pull request closed without merging**
