### PR TITLE
LPS-44217 SF

### PR DESCRIPTION
**Pull request by rotty3000**
this should replace https://github.com/adolfopa/liferay-portal/pull/1101 it contains integration tests and real UI

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79190. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/a2fbfe5bf5c9~1...a2fbfe5bf5c9)

**Pull request closed without merging**
