### PR TITLE
[TS] LPS-89922

### PR DESCRIPTION
**Pull request by brianikim**
Resending from https://github.com/adolfopa/liferay-portal/pull/851 with updated information and PR.

Hello @adolfopa ,

https://issues.liferay.com/browse/LPS-89922

The issue here is that when you attempt to add document types past the maximum number of types allowed in the creation menu in Documents and Media, the remaining document types are suppose to be displayed by clicking the "More" button that appears. However, clicking the button does nothing because we completely lack the implementation for Documents and Media.

The solution is to implement the feature.

Commit: 934a647 implements the basic features required for the "More" button to work. 
Commit: 6255072 implements a new search and filter method to handle not only keyword search of document types inside the More Menu frame, but also folder specific restriction checks to handle which document types should be displayed in the More Menu frame per folder. This is important because within each folder, you can restrict what document types can be added to the folder through Document Type Restrictions and Workflow setting when editing the folder.For your concern from the previous PR:

> I still don't understand why do we need to do further filtering on the document types. The inline permission helper should take care of that.

I have debugged to confirm that [inline permission helper](https://github.com/brianikim/liferay-portal/blob/c4689ad5d669824f0e15e34cb4c3ace0af286e7e/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFileEntryTypeFinderImpl.java#L339-L343) does not filter folder-specific document types.

Commit: 811278c is straightforward. Search needs to be done on everything, but the result needs to reflect pagination.

Commit: 0594693 and c4689ad are improvements to the folder-specific restriction check to ensure that we are properly searching using parentFolder if inherited.

Please let me know if you have any further questions. Thanks.

Sincerely,
Brian Kim 

Please let me know if you have any questions regarding the implementations.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@brianikim Just wanted to let you know I haven't forgotten about this, but I won't be able to send it today. Apologies in advance for the delay.

**Comment by brianikim** [comment]
Hello @adolfopa ,

No worries. I appreciate the update. Let me know if you have any questions.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
Hello @adolfopa ,

I will be rebasing the fix and re-sending you the PR.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
new PR with rebase: https://github.com/adolfopa/liferay-portal/pull/864

**Pull request closed without merging**
