### PR TITLE
LPS-110016,LPS-110017 Replace AlloyEditor in Body field in Message Boards

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:stable

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
@adolfopa I just fixed the SF errors for the `MBUtil` class, but I'm not sure how to solve the ones for the changes in `portal.properties` file. Let's talk about it when you have a change over slack.
Thanks!

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1363. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/97dbc3890163~2...97dbc3890163)

**Pull request closed without merging**
