### PR TITLE
LPS-92299 Remove useless code in VerifyBlogs

### PR DESCRIPTION
**Pull request by achaparro**
Hi @adolfopa,

You can remove the SF commit once you send it to Brian since I have already included that change here:
https://github.com/brianchandotcom/liferay-portal/pull/69706

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
ci:sf:test

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/69720

**Pull request closed without merging**
