### PR TITLE
LPS-71504 fix portlet crash when clicked article with default parent folderId

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by adolfopa** [comment]
Hey @arthurchan35 

Is this reproducible only in the EE branches? I've tried following the steps in master and it seems to work fine without your fix. Is there any extra step that is not in the Jira ticket that I may be missing?

Thanks!

**Comment by arthurchan35** [comment]
Hi @adolfopa ,

The original description: 
Add a Knowledge Base Article, and add a child article.
Add a Knowledge Base Display portlet.
Click on child article's title on the top left corner.

I am not on my work computer right now, so I am recalling from memory:
Here before clicking on the child article, you'll see that the parent article is listed in the left navigation section of display portlet, but after clicking on the child article, the parent article is no longer listed but instead only the child article is listed. The expected behavior is both parent and child articles should be listed.
And I was able to reproduce the issue before as I can remember. I will give it a try tomorrow asap.

Thanks,
Arthur

**Comment by arthurchan35** [comment]
Oh, can you try test it on a later build? Because it's a bug caused by a recent fix.

**Comment by arthurchan35** [comment]
I tested it again on the latest build, it is reproducible.

**Comment by arthurchan35** [comment]
HI @adolfopa ,
Have you gotten a chance to do test again?

**Comment by adolfopa** [comment]
Hey @arthurchan35 

Yes, I reproduced it with no problems (not sure what happened the other day). I'm gonna send you a pull with a little change. I've tested it locally, both LPS-71504 and LPS-71416, and everything seems to work fine. Could you confirm that everything works as expected? If that's so, ping me and I'll send to Brian.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/arthurchan35/liferay-portal/pull/13

**Comment by arthurchan35** [comment]
Hi @adolfopa 
I tested with your change, and it didnt work for LPS-71416, the issue remains.
steps to reproduce:
Create two articles, kb1, kb2 in root folder.
Create a child article for kb1 or kb2(using add child article button), eg. kb2_child.
In knowledge base display portlet, configure kb2 as parent resource in configuration.
Now, come back to the portlet, you will still see kb1 listed there, and if you click on it, you will see a warning saying: _"The article you requested was not found. This similar article may be useful to you."_

The reason behind it is that the configuration is actually used to take an article or folder as parent resource and then display **only** its children articles. However, the getRootResourcePrimKey() is actually named, because if you take a look at implementation of APIs used in getRootResourcePrimKey() (ie, APIs from KBUtil class), you will see they are only returning folderIds, which means it does not really handle cases when articles are configured to be parent. 

In my previous fix to LPS-71416, I actually made the change from getRootResourcePrimKey() to getParentResourcePrimKey(), then I realize getParentResourcePrimKey() isnt what I wanted, so in this fix, I changed it again to GetterUtil.getLong(portletPreferences.getValue("resourcePrimKey", null)); <---this attribute from frontend is actually used to retrieve the configured article/folder, see:https://github.com/liferay/liferay-portal/blob/master/modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/portlet/DisplayPortlet.java#L365

So I think, using GetterUtil.getLong(portletPreferences.getValue("resourcePrimKey", null)) is correct.

**Pull request closed without merging**
