### PR TITLE
LPS-60770

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/32733

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/32800. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/0992e42~1...0992e42) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2718. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/befca1a~2...befca1a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
