### PR TITLE
LPS-67377

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Hey @BryanEngler 

I've sent @jbalsas a different solution that I hope will fix all cases. See https://github.com/jbalsas/liferay-portal/pull/575.

Thanks!

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/327. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/03251f78c4eb~1...03251f78c4eb)

**Comment by jbalsas** [comment]
👀

**Pull request closed without merging**
