### PR TITLE
LPS-108570 change calls of FFDocumentLibraryDDMEditorConfiguration to use new Util

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa Remember to pull the changes (forced) :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84769. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/963cebe3449d~3...963cebe3449d)

**Pull request closed without merging**
