### PR TITLE
[TS] LPS-76604

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @daviddotzhang, @hhuijser,

Could you please explain the reason behind this change? It feels counterintuitive to return a configuration class name in a `getServiceName` method. 

I have searched for other usages of the same method and all of them consistently return the expected value:

```
modules/apps/collaboration/blogs/blogs-web/src/main/java/com/liferay/blogs/web/internal/exportimport/data/handler/BlogsPortletDataHandler.java
	public String getServiceName() {
		return BlogsConstants.SERVICE_NAME;
	}
--
modules/apps/collaboration/bookmarks/bookmarks-service/src/main/java/com/liferay/bookmarks/internal/exportimport/data/handler/BookmarksPortletDataHandler.java
	public String getServiceName() {
		return BookmarksConstants.SERVICE_NAME;
	}
--
modules/apps/collaboration/document-library/document-library-web/src/main/java/com/liferay/document/library/web/lar/DLPortletDataHandler.java
	public String getServiceName() {
		return DLConstants.SERVICE_NAME;
	}
--
modules/apps/collaboration/message-boards/message-boards-web/src/main/java/com/liferay/message/boards/web/internal/exportimport/data/handler/MBPortletDataHandler.java
	public String getServiceName() {
		return MBConstants.SERVICE_NAME;
	}
--
modules/apps/collaboration/wiki/wiki-web/src/main/java/com/liferay/wiki/web/internal/exportimport/data/handler/WikiPortletDataHandler.java
	public String getServiceName() {
		return WikiConstants.SERVICE_NAME;
	}
--
modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/exportimport/data/handler/AdminPortletDataHandler.java
	public String getServiceName() {
		return KBConstants.SERVICE_NAME;
	}
--
modules/apps/shopping/shopping-service/src/main/java/com/liferay/shopping/internal/exportimport/data/handler/ShoppingPortletDataHandler.java
	public String getServiceName() {
		return ShoppingConstants.SERVICE_NAME;
	}
--
modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/exportimport/data/handler/JournalPortletDataHandler.java
	public String getServiceName() {
		return JournalConstants.SERVICE_NAME;
	}
--
```

Thanks!

**Comment by daviddotzhang** [comment]
Hey @4lejandrito ，
**for knowledge base**.  the group service name is from "liferay-portal-ee/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/configuration.jsp".

"<portlet:param name="serviceName" value="<%= KBGroupServiceConfiguration.class.getName() %>" />"

**for Bookmarks**  the group service name is from "liferay-portal-ee/modules/apps/collaboration/bookmarks/bookmarks-web/src/main/resources/META-INF/resources/bookmarks_admin/configuration.jsp".

"<portlet:param name="serviceName" value="<%= BookmarksConstants.SERVICE_NAME %>" />".

**Comment by daviddotzhang** [comment]
@4lejandrito  according to my test, for "knowledge base", we can not simply change the "configuration.jsp" and AdminPortletDataHandler. this will cause NPE exceptions. since knowledge use different to get "kbGroupServiceConfiguration".
liferay-portal-ee/modules/apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/init.jsp
KBGroupServiceConfiguration kbGroupServiceConfiguration = ConfigurationProviderUtil.getGroupConfiguration(KBGroupServiceConfiguration.class, themeDisplay.getScopeGroupId());



BookmarksGroupServiceOverriddenConfiguration bookmarksGroupServiceOverriddenConfiguration = ConfigurationProviderUtil.getConfiguration(BookmarksGroupServiceOverriddenConfiguration.class, new GroupServiceSettingsLocator(scopeGroupId, BookmarksConstants.SERVICE_NAME));

**Comment by 4lejandrito** [comment]
Thanks for the explanation @daviddotzhang, now I have a much better understanding. 

Let me have a look and see if we can fix it "right". Otherwise I will make sure your fix works as expected and forward this PR.

**Comment by 4lejandrito** [comment]
Hi @daviddotzhang,

Can you please verify this change (https://github.com/daviddotzhang/liferay-portal/pull/15) fixes your issue? 

I have tested locally and it seems to work fine.

If you are happy with it let me know and I will forward it.

**Comment by daviddotzhang** [comment]
@4lejandrito 
/liferay-portal-ee/modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/upgrade/v1_0_0/UpgradePortletSettings.java

Should we change KBGroupServiceConfiguration.class.getName() to KBConstants.SERVICE_NAME ?

**Comment by 4lejandrito** [comment]
See https://github.com/daviddotzhang/liferay-portal/pull/16.

**Comment by daviddotzhang** [comment]
@4lejandrito it passed my manual test.

**Comment by 4lejandrito** [comment]
Hi @adolfopa,

See https://github.com/daviddotzhang/liferay-portal/pull/16.

**Comment by adolfopa** [comment]
Closing this in favor of https://github.com/adolfopa/liferay-portal/pull/670

**Pull request closed without merging**
