### PR TITLE
LPS-112571 Show the configured images

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Looks good to me. Rerunning tests; if everything passes, I'll forward to Brian.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
