### PR TITLE
LPS-86298 Using * as explicit wildcard

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
We need to make sure that the cached capabilities are cleared when the repository cache is cleared as well.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/64496.

**Pull request closed without merging**
