### PR TITLE
[TS] LPS-109296

### PR DESCRIPTION
**Pull request by balazssk**
Hi @adolfopa ,

If I understood correctly, the issue is that alternate URLs are redirecting when the i18nPath is the end of the URL and there is no 
trailing slash.

Can you please review?
https://issues.liferay.com/browse/LPS-109296

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
hi @adolfopa ,
Can you please share your thoughts about this change?
Thank you

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/585. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/3478563f9d1c~1...3478563f9d1c)

**Comment by adolfopa** [comment]
Sorry for the delay @balazssk, I was on vacation. To avoid this kind of blockers in the future, can you please send all the PRs targeted towards us to the liferay-lima user? All members of the team monitor that queue, so there's much less risk of things waiting for too long.

Thanks!

**Comment by balazssk** [comment]
Thanks for the review and info @adolfopa ,
Should have realised you were on vacation...

**Pull request closed without merging**
