### PR TITLE
LPS-67197

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Hey @zxdgoal @hhuijser 

While this fix works, it looks like the problem may be in another place. Do you have any extra information about why is it necessary to get the prefs directly from the DB? Are we getting stale prefs, or are the changes rejected for some reason?

Thanks!

**Comment by zxdgoal** [comment]
Yes @adolfopa 

After 7.0, referring to 
  
```
		LiferayPortletRequest liferayPortletRequest =
			getLiferayPortletRequest();

		PortletPreferences preferences = liferayPortletRequest.getPreferences();
```

When we made any changes from the configuration pop up in activities portlet, the ```liferayPortletRequest`` actually is from ``porlet-configuration-web``.

So 	``liferayPortletRequest.getPreferences();`` in fact is getting preference for module  ``porlet-configuration-web``, rather than ``social-activities-web``.

Not sure if we another way to getting prefs, instead of getting them from database directly?

Thanks
John.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/41900. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/8a017d8~1...8a017d8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
I've changed the implementation so that it uses the regular request to get the preferences instead of the LiferayPortletRequest. Ideally, request helpers should depend only on the request, so this will keep things a little bit cleaner.

Thanks a lot for the info @zxdgoal

**Pull request closed without merging**
