### PR TITLE
LPS-106891 Add a new configuration to allow configure google analytics

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83215. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/3381260202ac~3...3381260202ac)

**Pull request closed without merging**
