### PR TITLE
LPS-68603 Adding descriptive message for the error

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:retest

**Pull request closed without merging**
