### PR TITLE
[TECHNICAL-SUPPORT] LPS-68710

### PR DESCRIPTION
**Pull request by sergiogonzalez**
From @SGM3 

>My analysis of the issue shows that there were roughly two problem areas.

>The first was the child KB article seemed to place a (relative path) URL as the redirect which affected the back button functionality and what page is loaded on submit. This is dependent on the page used to access the child KB. Setting a full path URL seems to all unify the behavior and correct the functionality for the most part. Back button functionality was still broken, but you were still able to submit suggestions, until the URL became too long. This was covered in the first commit

>The second issue is what the I had mentioned last. The portlet was appending the current URL (with the current redirect parameter) to the new URL redirect parameter. The back button relied on the embedded redirect parameter it seemed and the URL itself was getting too long. This was covered in the second commit.

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
@SGM3 @sergiogonzalez Sorry for keeping this on hold for so long. We need to talk with the platform team about the URL length problem; while this fix works, we need a solution that fixes the general case, as we're experiencing similar problems in other applications.

Thanks!

**Comment by SGM3** [comment]
Has there been any conclusion about the URL length problem? Believe that was the primary issue in this LPP as well.

**Comment by adolfopa** [comment]
@SGM3 Sorry, nothing yet. I'll ping you when I have any news.

**Comment by SGM3** [comment]
Just making sure, no updates still, correct?

**Comment by adolfopa** [comment]
Yes, nothing yet :-( (btw, sorry for the late response @SGM3)

**Comment by SGM3** [comment]
Is there is status of this?

**Comment by adolfopa** [comment]
@SGM3 Sorry, there are no plans for general solution to the big url problem -- at least not in the short term. I've sent @sergiogonzalez an alternative fix to yours; see https://github.com/sergiogonzalez/liferay-portal/pull/3813

**Pull request closed without merging**
