### PR TITLE
LPS-44217 Added multi-host and locale integration test

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
@adolfopa this version of the PR should be directly backportable to 7.2.x

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79612.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79683.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80225.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80269. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/482fe100ef2e~1...482fe100ef2e)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/579. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/deb8464abb4a~2...deb8464abb4a)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/austinchiang/liferay-portal/pull/586. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/157c19e32b5b~4...157c19e32b5b)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80914. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/45d8b52d0db8~5...45d8b52d0db8)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81032. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/79cb9dd6ac85~9...79cb9dd6ac85)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81033. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/534d9d5a5cc0~4...534d9d5a5cc0)

**Pull request closed without merging**
