### PR TITLE
LPS-107030 Table alignment

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/292. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/501709f59954~1...501709f59954)

**Pull request closed without merging**
