### PR TITLE
LPS-123723

### PR DESCRIPTION
**Pull request by hhuijser**
Looks good!

Failure in `BlogEntriesDisplayContextTest` seems related though and you can fix that much faster than me :)
You can send straight to Brian after that.

### CODE REVIEW

**Comment by hhuijser** [comment]
ci:test:sf

**Comment by hhuijser** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/1084. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/6441d7bd11aa~1...6441d7bd11aa)

**Pull request closed without merging**
