### PR TITLE
[MB Tuning] LPS-96609

### PR DESCRIPTION
**Pull request by yuhai**
Hi @adolfopa

This is a pull for MB performance tuning. Could you review it in case we break anything? 

We found the [custom sql ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/message-boards/message-boards-service/src/main/resources/custom-sql/default.xml#L257-L272) created the temp table in mysql side through using mysql workbench tool. And this will increase the sql executed time.

Refer to the mysql [document](https://dev.mysql.com/doc/refman/5.7/en/internal-temporary-tables.html), "COUNT(DISTINCT)" will create temp table. 

By the way, we will run the white paper's test next Friday, could you please take this priority if possible?

cc @dantewang

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74570

**Pull request closed without merging**
