### PR TITLE
LPS-108455 Generate XMLBeans with Axis2 from WSDL

### PR DESCRIPTION
**Pull request by cgoncas**
This pull only will generate the XMLBeans, in a follow-up, we will migrate all the code to use the new libs.

A file generated/.touch is included, so ant all won't try to generate the XMLBeans.

Thanks!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84474.

**Pull request closed without merging**
