### PR TITLE
LPS-86131 General update of the getResolvedModuleName inside *DisplayContext pattern

### PR DESCRIPTION
**Pull request by jbalsas**
/cc @ealonso

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:stop

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test

**Comment by adolfopa** [comment]
See https://github.com/jbalsas/liferay-portal/pull/1596

**Pull request closed without merging**
