### PR TITLE
LPS-71557

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
I think that this will have some rebase conflicts with https://github.com/adolfopa/liferay-portal/pull/497

**Comment by adolfopa** [comment]
The other one is in Brian's queue (https://github.com/brianchandotcom/liferay-portal/pull/48071). I'll review and send this tomorrow.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48115

**Pull request closed without merging**
