### PR TITLE
LPS-103923 integrate data engine taglib on jsp

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84399. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/3f881e5bf16b~3...3f881e5bf16b)

**Pull request closed without merging**
