### PR TITLE
[Support Ticket] LPS-84064

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
Hey @adolfopa 

For what this ticket tries to do, see the detailed description of https://issues.liferay.com/browse/LPS-84064

Basically we have two issues when dealing with this ticket:

1. We can't simply do https://github.com/tinatian/liferay-portal/pull/965 because it causes wrong resource bundle to be used by "site administration" part in the product menu (and there will be more I assume).
2. We do want to avoid blindly aggregate the `PortletConfig` based `ResourceBundleLoader` with the others, because in most situations it's same with the one fetched using servlet context name.

And the two points above are exactly same with what you mentioned in https://github.com/brianchandotcom/liferay-portal/pull/33622, the "Sometimes the wrong resource bundle gets used" part.

Could you review this PR and point out if there's anything wrong, or give us suggestions? Thank you very much!

cc @peterpetrekanics @tinatian

**Comment by adolfopa** [comment]
Hey @dantewang 

I don't see anything wrong with this PR. Thanks for the detailed explanation!

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/62275

**Comment by adolfopa** [comment]
Can you guys handle the backport? Thanks!

**Pull request closed without merging**
