### PR TITLE
[TS] LPS-91380

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-91380

Please let me or @jrao know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68874

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68874

**Pull request closed without merging**
