### PR TITLE
LPS-100969 Extract titleConcatenator logic to test it

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79577. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/b1cd86098d39~7...b1cd86098d39)

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/79577

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79686. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ea23200b6ea0~8...ea23200b6ea0)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79743. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/497bdb3cd8b7~9...497bdb3cd8b7)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79818. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/a5c7e9edb92c~9...a5c7e9edb92c)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79833. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/a5c7e9edb92c~9...a5c7e9edb92c)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79866. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/d0efb2430df6~10...d0efb2430df6)

**Pull request closed without merging**
