### PR TITLE
LPS-108673 Auto SF.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reopen

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84849. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/56a9e1ceeab8~1...56a9e1ceeab8)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84850. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/3a0803af061e~1...3a0803af061e)

**Comment by adolfopa** [comment]
Just started reviewing :)

**Pull request closed without merging**
