### PR TITLE
LPS-96880 FriendlyURLLocalization is not being imported when companyId is not default

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
Hey @adolfopa, did you have a chance to review this?

Thanks in advance.
BR,
Jorge

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/75815

**Pull request closed without merging**
