### PR TITLE
LPS-113512 Vocabularies associated with other document types are presented for Basic Document

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @adolfopa 

Could you please review this pull request?

The root cause of the issue is that `fileEntryTypeId` is -1 (not defined) if a basic document is created. I don't know if this is intended or not, but on 7.1.x the `fileEntryTypeId` is 0 by default.

I used two methods to solve the issue, each in their own commits, but I'm not sure which one to go with.

Thank you and best regards,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/37.

**Comment by adolfopa** [comment]
Hey @IstvanD 

Can you send any future PRs to the "liferay-lima" Github user? We're trying to get all team's work visible under that user.

Thanks!

**Comment by IstvanD** [comment]
Hi @adolfopa 

OK, I'll try to keep that in mind. :)

Best regards,
István

**Pull request closed without merging**
