### PR TITLE
[TS] LPS-112274

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1413.

**Comment by adolfopa** [comment]
See https://github.com/adolfopa/liferay-portal/pull/1413

**Pull request closed without merging**
