### PR TITLE
LPS-66550

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hi Adolfo,

This fix has already been mostly reviewed by @sergiogonzalez on https://github.com/sergiogonzalez/liferay-portal/pull/3251 The biggest change here is in https://github.com/adolfopa/liferay-portal/commit/c3259f66626775a320680e35ec950ccdeeca1dc1

Notes from @ericyanLr:

> LPP Ticket: https://issues.liferay.com/browse/LPP-21562
> 
> **To recap:** 
> The main goal of these changes is to improve on the email notifications that are originating from a Message Board thread.
> Currently, email notifications originating from the same thread, do not create a **proper email thread** in email clients, such as gmail and thunderbird.
> 
> **Changes to resolve this issue**
> 1. Make sure the message subject's prefix (RE:) is appended to the front of the subject line.
> 2. Make sure the message-id assigned to the email is unique and can also be retrieved from the database.
>    - This issue mainly affects databases that do not properly retain milliseconds, mainly MYSQL.
>      MYSQL 5.5 truncates the milliseconds whereas 5.6 and 5.7 rounds the milliseconds.
> 
> Examples of these issues can be seen in the related LPP Ticket: [LPP-21562](https://issues.liferay.com/browse/LPP-21562)
> 
> **Structure of the commits**
> - The majority of the commits are for resolving Change # 1.
> - Change # 2 is resolved by this commit: https://github.com/adolfopa/liferay-portal/commit/c3259f66626775a320680e35ec950ccdeeca1dc1

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @jonathanmccann @ericyanLr 

Why do you guys need to truncate the date? Can you elaborate a little bit more on the commit message "LPS-66550 Truncate the modified date by excluding the milliseconds to properly maintain a unqiue message-id; this is to account for databases that round dates, such as mysql". Why don't we need the miliseconds? What's the issue?

Assuming that we really need to truncate the date, since this is something  that we only need for the messageId, we should do it in a different place instead of doing it in the model because otherwise we are truncating this for everyone and not only for the message id.

Then we should create a method in the MBMessageLocalServiceImpl that truncates the date and invoke that method when invoking

```
		subscriptionSender.setMailId(
			MBUtil.MESSAGE_POP_PORTLET_PREFIX, message.getCategoryId(),
			message.getMessageId(), modifiedDate.getTime());
```

we won't use modifiedDate.getTime but the new method that will truncate it.

Let me know if you guys have any question.

Thanks!

**Comment by ericyanLr** [comment]
Hey @sergiogonzalez,

Apologies for not providing much information regarding the date truncation.
This issue is a bit difficult to explain, but I'll try my best.
First, here is a link to the support forum thread with details and examples regarding the MYSQL issue:
https://in.liferay.com/web/support/forums/-/message_boards/message/23622434

**Main Issue**
The issue is that MYSQL does not actually retain the milliseconds.
In MYSQL 5.5, they would truncate the milliseconds.
In MYSQL 5.6/5.7, they would round the milliseconds.

This makes it problematic for being able to create AND retrieve the same "Unqiue Message-id".
For this case, we would have to consider 2 things:

1. The modified date created as a Java Date object when a new MBMessage is first created
   * This includes the original milliseconds
2. The actual modified date that is stored in the database (Depends on MYSQL version)
   * This will either truncate or round the milliseconds

**Sample Scenario:**
A new message board thread is created and generates a message-id:
> Message-ID: <mb_message.0.21301.1470095228543@events.liferay.com>

As long as the object remains in cache, it will retain the original modified above:
> Message-ID: <mb_message.0.21301.1470095228543@events.liferay.com>

If we clear the entity cache, and retrieve the message-id for the same message, it will be different depending on the MYSQL version.
> 5.5: Message-ID: <mb_message.0.21301.1470095228000@events.liferay.com>
> 5.6: Message-ID: <mb_message.0.21301.1470095229000@events.liferay.com>
> 5.7: Message-ID: <mb_message.0.21301.1470095229000@events.liferay.com>

At this point, if we were to handle truncating the milliseconds when generating the unique message-id, it would be too late. The stored modified date in the database would already have been truncated/rounded by MYSQL. 

**Why we chose to do it in the model**
We thought of several solutions to resolve this issue, and came up with a few approaches, which can be seen in the message board forum. 

What makes it difficult is that the method to notify subscribers is called within the Hibernate Transaction.  

Since the modified date could be rounded or truncated when being stored in the database, we decided on this solution, which would truncate the date beforehand.  This would handle the issue of MYSQL truncating/rounding the date.

**Side Note**
Liferay DXP supports MYSQL 5.6 and 5.7
Liferay 6.2 supports MYSQL 5.5 and 5.6.

MYSQL 5.5 is mentioned, since the original ticket involves a client on Liferay 6.2.

----
Please let me know if you have any questions.
Thanks!

**Comment by sergiogonzalez** [comment]
Hey @ericyanLr I think that I understand the issue, but I still don't understand why we need to truncate the modified date in the model.

If we have a util method that truncates or manages the modifiedDate of the message every time we need to create the messsageId it should work because no matter if we obtain it directly from the MBMessage object or from the database, we will always truncate the modified date to convert it to the message-id.

So basically, what I propose is that anytime we create or get the message id like mb_message.<whatever-date> we invoke the logic to truncate or massage the modified date as required. By doing this we should always ensure that the id is consistent. 

For example, with the data you provided:

`mb_message.0.21301.1470095228543@events.liferay.com`
`mb_message.0.21301.1470095228000@events.liferay.com`
`mb_message.0.21301.1470095229000@events.liferay.com`
`mb_message.0.21301.1470095229000@events.liferay.com`

As long as we truncate in the appropriate number they should be consistent, right?

**Comment by ericyanLr** [comment]
Hey @sergiogonzalez,

We have also considered modifying the modified date as required when generating the message-id, but the difficult part is implementing a logic that would know whether to round or truncate the date based on the database the instance is using.

Here are two scenarios to illustrate the issues that made us ultimately consider making this change in the model.

**Initial Scenario**
A user creates a new thread and an email is sent to a subscriber. The modified date is created in java (which includes milliseconds): **1470095228543**.
* An email is sent with the following **message-id**: 
    * `mb_message.0.21301.1470095228543@events.liferay.com`

A comment is now added to the created thread and an email is sent to the same subscriber.  The modified date is still using the same date, which has been cached: **1470095228543**.
* An email is sent with the following **In-reply-to** (references the original message): 
    * `mb_message.0.21301.1470095228543@events.liferay.com`

We now clear the entity cache in the Liferay instance (or restart the portal). This will make Liferay retrieve the modified date stored in the database.

**Scenario 1 - If the instance uses: MYSQL 5.5 (truncates dates)**
A comment is now added to the created thread and an email is sent to the same subscriber.
Note:  the modified date now retrieves the modified date from the database: **1470095228000**.
* An email is sent with the following **In-reply-to** (references the original message): 
    * `mb_message.0.21301.1470095228000@events.liferay.com`

**Scenario 2 - If the instance uses: MYSQL 5.6/5.7 (rounds dates)**
A comment is now added to the created thread and an email is sent to the same subscriber. 
Note: the modified date now retrieves the modified date from the database: **1470095229000**.
* An email is sent with the following **In-reply-to** (references the original message): 
    * `mb_message. 0.21301.1470095229000@events.liferay.com`

----
To recap the scenarios, here are the emails that were sent:
* Email 1: Sent when the first thread was created
    * modified date: **1470095228543**
* Email 2: Sent when the first comment was created
    * modified date: **1470095228543**
* ----Cleared Entity Cache----
* Scenario 1 - Email 3: Sent with another comment, but using MYSQL 5.5 (truncates date)
    * modified date: **1470095228000**
* Secnario 2 - Email 3: Sent with another comment, but using MYSQL 5.6/5.7 (rounds date)
    * modified date: **1470095229000**

**Rounding the modified date when generating the message-id**
If we decide to now truncate the modified date when generating the message-id, the issue is that the generated message-id may not be consistent with MYSQL 5.6/5.7.

**Scenario with implemented logic to truncate modified date + MYSQL 5.6/5.7 (rounds date)**
Truncate modified date **1470095228543** --> **1470095228000**
* Email 1: Sent when the first thread was created
    * modified date: **1470095228000**
* Email 2: Sent when the first comment was created
    * modified date: **1470095228000**
* ----Cleared Entity Cache----
* Email 3: Sent with another comment, but using MYSQL 5.6/5.7 (rounds date)
    * modified date: **1470095229000**

----
Please let me know if you have any questions.
Thanks!

**Comment by sergiogonzalez** [comment]
Hey @ericyanLr thanks for the detailed explanation, it has been really useful.
However, I don't think that we should still have that logic in MBMessageImpl and we need to find a workaround for it.

Instead of truncating the numbers we could use a different approach. What about instead of passing `modifiedDate.getTime()` as a parameter to `subscriptionSender.setMailId` we use a specific format? Something like:

```java
		DateFormat dateFormat = DateFormatFactoryUtil.getSimpleDateFormat(
			"yyyy-MM-dd'T'HH:mm:ss");

		dateFormat.format(modifiedDate.getTime());
```

Then, as we don't care about the milliseconds the dateFormat would be the same no matter the database and it will still preserve the uniqueness of using the modifiedDate with an error of seconds, that I think it's enough.

This fix doesn't require us to change the setModifiedDate method which is something that we shouldn't do.

What do you think?

Thanks!

**Comment by ericyanLr** [comment]
Hey @sergiogonzalez, I agree that it would be best if we did not need to introduce this logic into MBMessageImpl.

**Issue with using date format**
The main issue is that we are relying on the modified date to generate a message-id that must be both: unique and retrievable.

If we were to use the date format, it would have an error of seconds, as you have stated.
To clarify, here are the example milliseconds converted to actual dates:
* Modified date is first created (Java Object)
    * Milliseconds: **1470095228000**
    * Date: **Mon Aug 01 2016 23:47:08**
* Entity cache is cleared and Modified date is retrieved (MYSQL 5.6/5.7)
    * Milliseconds: **1470095229000**
    * Date: **Mon Aug 01 2016 23:47:09**

Since the milliseconds are either rounded or truncated depending on the database version used, the modified date could always change by +/- 1 second.

Once the time is off by 1 second, the retrieved message-id for the message no longer matches the original message-id and is treated as though it was another email.  This would break the email thread and start a new thread.

**Note:** The concern for the precision of the modified date is more-so for the message-id generation rather than retaining a precise modified date in the database.

**Another Approach**
Another approach, that is also messy, would be using a Transaction Commit Callback.  We considered using this approach, but went with the approach of introducing the logic to MBMessageImpl.

Do you think using a Transaction Commit Callback would be a considerable fix?

Thanks!

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sergiogonzalez** [comment]
Hey @ericyanLr 

Thanks again for your answer. Before considering the TransactionCommitCallback I'd like to fully understand this approach because I think it's doable and it seems easier.

I think that we found the final fix :) @adolfopa proposed that instead of using the modified date, we use the message uuid. That would ensure the uniqueness of the mailid and it's stored in the database, so it's not random and it can be obtained to generate the inReplyTo.

Can you give that a try?

Thanks!

**Comment by ericyanLr** [comment]
Hey @sergiogonzalez @adolfopa,

We have also considered depending on the message uuid to make it unique, but I found out that because it is a message board, we allow users to update their original posts.
When a user modifies their thread, a separate email notification is sent and the MBMessage would still have the same message uuid.

This means that when a user first creates a message, an email is sent with the message uuid.
If the user then updates the message, another email is sent with the same message uuid.
This means that the message-id would not be unique in this case if we do not utilize the date.

**Sample Scenario:**
* Create a new Thread: **TestThread**
  * UUID: 12b95f93-59a1-7b83-ea69-9e0cda537702
  * Message-ID: <mb_message.0.32733.1472065411152@events.liferay.com>
* Create a reply to the thread above
  * UUID: bca19646-5041-b3ba-49df-5ae1c592ce87
  * Message-ID: <mb_message.0.32742.1472065424738@events.liferay.com>
  * In-Reply-To: <mb_message.0.32733.1472065411152@events.liferay.com>
* Update original thread: **TestThread**
  * UUID: 12b95f93-59a1-7b83-ea69-9e0cda537702
  * Message-ID: <mb_message.0.32733.1472065514339@events.liferay.com>

**Analysis**
Since the MessageBoards allows us to update our original posts, the UUID will remain the same, but the content will be different.  The "Update Message" that is sent as a notification requires a unique message-id as well. If we do not include the date, using the UUID would not provide a unique message-id.

During an update, the only change in the database for MBMessage is the subject, body, and dates.

**Random Thought**
While analyzing this, I had a random thought of incorporating the subject and body for the unique id. If we created a hash using the subject and body, such as an md5 hash, it would generate a somewhat unique string.

But, after further testing, I found that if we update a message board thread, without changing the subject and body, it would still update the database and send an email notification.

At this point, it looks like we still need to depend on the modified date.

Please let me know if you have any questions.
Thanks!

**Comment by sergiogonzalez** [comment]
Hey @ericyanLr 

After all this long discussion :) I think that we end up having to choose one of the following options:

1. Apply the approach of updating the setModifiedDate method. 
2. Apply the fix using the Uuid instead of the modified date and assume that in case the user edits an existing message, it will have the same messageId instead of a unique one.
3. Create a new column in MBMessage to store the messageId. This message Id would be created when a new message is added and it will be updated in the case the mbMessage is updated. This messageId could be built without using the modifiedDate and using a uuid instead. 

I strongly disagree with option no.1 because I don't think it's the appropiate fix.

The option that seems more appropriate in the long term is no.3, because its easier to maintain and less likely to have bugs, although it might look a little bit overkilling. However, I don't think that we can easily backport this to a fix pack because we cannot modify the database model and include a new column. Then, for the fix pack, we would need to store this information in a new table (or expando) and write an specific upgrade for customers so when the upgrade to Liferay 7.1 or 8, we move the data from the temporal table or expando to the final destination, while users upgrading from CE 7 GA1 they will need a completely different independent upgrade path.

Regarding option no.2 I think that it's the easier thing we can live with in a fix pack, because it fixes most of the scenarios except updating a previously published message, and even in that case it's not a very big deal that the message id are not unique.

I wanted to share this options with you to see your thoughts on it.

I'm also copying @dsanz as the SME of Collaboration to also get his input in this matter.

Thanks!

**Comment by ericyanLr** [comment]
Hey @sergiogonzalez,

I agree with your response. Let's try to work on option no.2 and see where that takes us.

For option no.2, here are the discussed topics regarding the changes:
* We will be using the UUID instead of the modifiedDate for the message-id
* We understand that we may not always be following the Email Standard completely [RFC-2822](https://tools.ietf.org/html/rfc2822#section-3.6.4).  This means that the message-id will not always be unique.
  * Case: **Updating a message thread**
    * Updating a message thread would send an email to subscribers using the same message-id as the original message thread.
    * Subsequent updates will continue to use the same message-id as the original message thread.
  * Case:  **Updating a comment in the message thread**
    * Same case as updating a message thread.

**Testing**
I have tested using the UUID instead of the modified date with GMAIL as the email provider.
The emails received from creating/updating the same message thread all have the same message-id and are displayed as a proper email thread.

I have not tested any other email providers, as well as email clients, to see if having duplicate message-ids would be an issue.

**Next Steps**
Please help verify if everything above is correct and whether we should proceed with creating the fix for option no.2.

Thanks!

**Comment by sergiogonzalez** [comment]
Bien cerrado @adolfopa, bien!

**Pull request closed without merging**
