### PR TITLE
LPS-90800 Remove and deprecate non used image gallery property

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@adolfopa errors seem unrelated, see https://github.com/brianchandotcom/liferay-portal/pull/68221

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/68248

**Pull request closed without merging**
