### PR TITLE
LPS-106977 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83323

**Pull request closed without merging**
