### PR TITLE
LPS-69728 - A regular site member user is unable to view or edit their saved drafts when replying to a Message Board thread

### PR DESCRIPTION
**Pull request by daviddotzhang**
Hey @adolfopa

I removed the part of code added LPS-42294, this might cause an issue that the "next and previous" will include the drafts.

Q1, For the master, do we have removed the function of "next and previous" of thread messages?

Q2, For the master, do you think we need also to enable drafts for threads? (_Add a thread, save as a draft, it does not show)_

Thanks,
David.

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Hey @daviddotzhang 

Thanks a lot for letting me take at look at this :-)

About Q1, it seems all that logic is now handled by the MBTreeWalkerImpl class, and it looks like it is not taking into account the trashed entries. So, you're right, that will probably cause problems (though I'm not 100% percent sure, I havent't tested it yet).

About Q2, where aren't they showing up? In the "My Posts" section, in the thread or in none of them? At least, I think both cases should be consistent, i.e. if we show draft replies in a section, we should do the same with threads, and viceversa.

I'm also CC'ing @sergiogonzalez so that he can take a look at this and maybe give you more information.

Thanks!

**Comment by daviddotzhang** [comment]
Hey @adolfopa 

1: Is the fix for the issue OK for you ?

2: Is the right way to fix it ?

Regards,
David.

**Comment by adolfopa** [comment]
Hey @daviddotzhang 

We believe the proper fix is to modify the underlying query, so that it returns all entries with the given status OR those which are owned by the current user. The problems I see with this fix are:
  - (relatively minor) A possible performance problem, as all messages in a thread are returned, and it is necessary to iterate over all of them.
  - This breaks the pagination. The total/page count will not be accurate, as you're filtering out messages  after calculating it. The end result is that some pages will have less items than expected (in some cases, it could even be empty).

Thanks!

**Comment by adolfopa** [comment]
@daviddotzhang Can you implement the changes I described in the previous comment or do you prefer for us to do it?

**Comment by daviddotzhang** [comment]
Hey @adolfopa I hope you can help on the fix.

Thanks in advance.
David.

**Comment by adolfopa** [comment]
Sure, I'll handle this.

**Comment by adolfopa** [comment]
Fix merged.

**Pull request closed without merging**
