### PR TITLE
[TECHNICAL SUPPORT] LPS-96651 Avoid using original inputStream as it will be consumed and Tika won't be able to extract text

### PR DESCRIPTION
**Pull request by jorgediaz-lr**

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
CI test failures seem to be unrelated to my changes

**Comment by jorgediaz-lr** [comment]
Hi @adolfopa 

Please review this PR as I need to backport it to 6.2.x as part of LPS-66608 and LPS-81513 backport, more information see: https://github.com/liferay/liferay-portal-ee/pull/14566

Thank you

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74430

**Pull request closed without merging**
