### PR TITLE
LPS-85733 Adding test case to verify converted Media: tags

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @IstvanD 

It seems to work as expected. Anyway I've talk with @adolfopa. 

From an arquitectural point of view, it doesn't seem to be the best option, so he'll take a look in order to improve it if possible.

Thanks!!

**Comment by robertoDiaz** [comment]
ci:test

**Comment by IstvanD** [comment]
ci:reopen

**Comment by IstvanD** [comment]
Hey @adolfopa 

I was wondering if you could find the time to take a look at the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hey @adolfopa 

Are there any updates on this case?
Please let me know if you need any help or explanation.

Thank you,
István

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/64456

**Pull request closed without merging**
