### PR TITLE
[TS] LPS-100082

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-100082

Hi Adolfo,

This PR contains no functional changes, only naming changes for the finder methods originally added in LPS-100082.  Without the changes added in this PR, there is no way for LPS-100082 to be backported without introducing a major version increase or breaking changes.

Please let me know if you have any questions, thanks!

 CC @Joshuacords

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85025.

**Pull request closed without merging**
