### PR TITLE
LPS-105401 test to check relation on staged group

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81974. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/6da716b4eeaf~1...6da716b4eeaf)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/82032. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/17a2358f1210~1...17a2358f1210)

**Pull request closed without merging**
