### PR TITLE
LPS-68127 Returning reading time from 0 to X minutes and hiding it if it is 0

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45354. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/5f26b61~3...5f26b61) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3628. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/cee5b3f~4...cee5b3f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
