### PR TITLE
LPS-69486 Notification delivery email checkbox gets ignored for private messages

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by IstvanD** [comment]
Hello Guys,

I'm wondering, are there any updates on this?

Thank you.
István

**Comment by adolfopa** [comment]
Sorry for the delay. I'll review and push this today.

**Comment by IstvanD** [comment]
Thank you Adolfo!

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/45516. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/041b95c~1...041b95c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
