### PR TITLE
LPS-103071 Allow users with permission to see the staging group see the content of this group.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by IstvanD** [comment]
Hi @adolfopa 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79936. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/3b4a6c0097d2~1...3b4a6c0097d2)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79937. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/be7a09f52513~1...be7a09f52513)

**Pull request closed without merging**
