### PR TITLE
[TS] LPS-80220

### PR DESCRIPTION
**Pull request by arthurchan35**
From https://github.com/adolfopa/liferay-portal/pull/679

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
ci:retest

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58590

**Pull request closed without merging**
