### PR TITLE
LPS-135706

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Adolfo,

I'm sending this pull request to you since I think @robertoDiaz already discussed this solution with you ([PTR-2553](https://issues.liferay.com/browse/PTR-2553)). Let me know if I should send this pull request to a different user instead.

https://issues.liferay.com/browse/LPS-135706

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:sf

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @mbowerman 

Can you send the PR to the user liferay-lima? In general, we try to avoid sending PRs to individual users.

Thanks!

**Comment by mbowerman** [comment]
Resent at https://github.com/liferay/liferay-portal/pull/4301

**Comment by mbowerman** [comment]
Resent at https://github.com/liferay-lima/liferay-portal/pull/2066

**Pull request closed without merging**
