### PR TITLE
LPS-109062 Use asset-library instead repository

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85099. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ca10ee080626~1...ca10ee080626)

**Pull request closed without merging**
