### PR TITLE
LPS-70957 Remove unused import

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by sergiogonzalez** [comment]
@sharonchoi could you please take a look at the tests to see if they are real and if there's something  that we need to fix? Thx!

**Comment by sharonchoi** [comment]
sure, will do

**Comment by sharonchoi** [comment]
Hey @adolfopa,

I fetched this pull and ran the tests locally, and the failures seem unrelated. Errors are also seen on other pull request results run in a similar timeframe, see: https://github.com/brianchandotcom/liferay-portal/pull/47941#issuecomment-289988956

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/47974

**Pull request closed without merging**
