### PR TITLE
LPS-61337

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Hey @bejondshao,

I don't think that ignoring errors is a good idea. We should refactor the `moveFolders` method so that instead of interleaving the copy+delete operations, it first copies everything and then, if no error occurred, deletes the source folder. In the worst case, we'll leave garbage in the store, but no data loss will occur and users will get notified of any errors.

What do you think? Do you have time to make those changes?

**Comment by bejondshao** [comment]
Hi adolfopa,

copy+delete operations are changed in https://issues.liferay.com/browse/LPS-60884. In LPS-60884, it really causing lost data, even though I enable trash.

subfolderA is moved successfully (so it's deleted first) while subfolderB meets exception. It already causing loss data.

Besides, move file in the same site would be ok even though the file is lost in file system. So my fix is according to that behavior.

Would you consider it again?

Thanks

**Comment by bejondshao** [comment]
My fix is aim to avoid throw excpetion. Because when exception is thrown, the file system gets inconsistance. We can suggest customer to use refactor, but we can't make customer not to call Liferay API directly.

**Comment by adolfopa** [comment]
Hey @bejondshao,

What I mean is not to force our customers to refactor their code, but to change the implementation of `moveFolders` so that it does its thing in two different phases:
1. Recursively copy the folder to the destination
2. If everything went well, delete the source folder; otherwise, delete the target folder.

Basically, the problem with the current implementation is that on each recursive call, it copies *and* deletes each element, so that on failure, there's no way to rollback the filesystem changes. If we first copy everything and then, delete only when all operations are successful, there would be no loss of information. Also, the API would suffer no changes so the customers shouldn't be affected.

**Comment by bejondshao** [comment]
Hi adolfopa,

Please see https://github.com/hhuijser/liferay-portal/blob/78e601820f11e7c3e94b75606e66407a897b7f6b/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppServiceImpl.java#L3108-L3114
and 
https://github.com/hhuijser/liferay-portal/blob/78e601820f11e7c3e94b75606e66407a897b7f6b/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppServiceImpl.java#L3140-L3142

Suppose FolderA contains SubFolder1 and SubFolder2, when we move FolderA, recursive calls will happen. After copying SubFolder1, it will delete SubFolder1 with #L3140-L3142, right? So SubFolder1 does no longer exist in the source site. Then it will try to copying SubFolder2, it throws exception. Ok, database rollback, including SubFolder1 and its files.

Your opinion is that when we move FolderA, it will copy SubFolder1 and SubFolder2, then delete FolderA. Actually, after copying SubFolder1, it will delete SubFolder1 directly. That's the root cause, it doesn't matter with moving file.

**Comment by adolfopa** [comment]
Hey @bejondshao 

I've made the changes I was talking about, because I think it will be easier to have some code to talk about. See https://github.com/sergiogonzalez/liferay-portal/pull/2772

After reviewing, he will send the PR to you so that you can review it and verify that it doesn't break anything. We won't merge it until you give the ok.

Thanks!

**Pull request closed without merging**
