### PR TITLE
LPS-67752 - Message Boards portlet is sorting threads oldest to newest instead of newest to oldest

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey @adolfopa
Could you help to review this pull request as high priority as one customer is waiting for this fix?

Thanks,
Dale

**Comment by sergiogonzalez** [comment]
ci:reopen

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43885. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43890. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/02bcf44~1...02bcf44) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43895. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/32f5206~1...32f5206) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43949. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/f6f7316~1...f6f7316) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43957. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/c4c54aa~2...c4c54aa) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/361. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/bbef42a~2...bbef42a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/362. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ed130ad~2...ed130ad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43981. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ed130ad~2...ed130ad) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
