### PR TITLE
LPS-109256 Build lang.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85350. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/5cc32742b5c4~2...5cc32742b5c4)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85390. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/d63335d1bcd0~2...d63335d1bcd0)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85396. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/4a1323f23ee3~2...4a1323f23ee3)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85404. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/c8b00833be2e~2...c8b00833be2e)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85442. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/212a00b102e2~2...212a00b102e2)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85464. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/97e77a15b7a0~2...97e77a15b7a0)

**Pull request closed without merging**
