### PR TITLE
Lps 109315

### PR DESCRIPTION
**Pull request by SamZiemer**
/cc @brianikim

Notes from Brian:
> https://issues.liferay.com/browse/LPS-109315
> 
> We introduced an arbitrary cap of 50 for unique file name tries in which we stop adding (#) suffix at the end of duplicate file names after 50 tries.
> 
> The fix is to make the value configurable.
> 
> Sincerely,
> Brian Kim

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1309. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/8f9023a36c04~3...8f9023a36c04)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85834. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/8f9023a36c04~3...8f9023a36c04)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1312. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/07e438da5b70~5...07e438da5b70)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85936. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/026eb1fe1a9a~5...026eb1fe1a9a)

**Pull request closed without merging**
