### PR TITLE
LPS-110735 Baseline

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward seems like a CI issue
```
start-app-server-preserve-liferay-home:
[beanshell] Waiting for server startup message
FATAL: command execution failed
java.nio.channels.ClosedChannelException
```
@yichenroy

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
