### PR TITLE
LPS-94075 Change subfolder key to folder - Bookmarks

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/72315

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/950. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/44c79e32b577~1...44c79e32b577)

**Pull request closed without merging**
