### PR TITLE
[TECHNICAL-SUPPORT] LPS-67188 Knowledge Base Display navigation should display an article hierarchy in tiers, no matter its depth

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @adolfopa 

Could you please check this pull request?

[LPS-67188](https://issues.liferay.com/browse/LPS-67188) was opened as a Story ticket in the past, but since a customer reported that issue recently, I assigned it to myself and implemented a solution.

Please feel free to forward the pull to the actual KB reviewer if you are not the one.

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3443. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/07db706~9...07db706) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
@IstvanD I've made the behaviour configurable, so that the user can choose how the navigation menu behaves. Could you please take a look to check it still satisfies the customer's needs? By incrementing the 'max nesting level' parameter in the portlet configuration you should get the desired behaviour.

Thanks <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by IstvanD** [comment]
Hey @adolfopa 

Thanks for taking care of the code and adding the corrections.
I'll let you know what the customer thinks of the solution.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/IstvanD/liferay-portal/pull/22. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ace718a~10...ace718a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42958. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ace718a~10...ace718a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42987. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/24d130d~11...24d130d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
