### PR TITLE
LPS-98497 Pass discussion element for the taglib

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
@robertoDiaz will try to simplify the fix by passing the correct userId directly.

**Comment by rgusztus** [comment]
Hi @adolfopa,

Hope you're doing fine.
My reason for passing the discussion element instead of the userId was to keep consistency as a few other portlets, like blogs for example is working at the same way, so I wanted to have the same behavior everywhere.

Regards,
Robert

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by adolfopa** [comment]
@robertoDiaz will look at this.

**Pull request closed without merging**
