### PR TITLE
LPS-111637 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jpince** [comment]
PMD failure fixed here: https://github.com/brianchandotcom/liferay-portal/pull/87389/commits/eec585d32c991580c3c931fab61cf9af85deabee

**Comment by adolfopa** [comment]
See https://github.com/adolfopa/liferay-portal/pull/1391

**Pull request closed without merging**
