### PR TITLE
LPS-69306 update API for stores

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by mdelapenya** [comment]
ci:reopen

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mdelapenya** [comment]
ci:retest

**Comment by mdelapenya** [comment]
Hey @adolfopa, I resent over same PR, with one commit more, but also rebased with master (there were conflicts on DBResigtrator, which was deleted)

Please review whenever you can

Thanks!

**Comment by mdelapenya** [comment]
ci:retest

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
