### PR TITLE
[TS] LPS-109353

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85394. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/5cd5b4c7d5eb~2...5cd5b4c7d5eb)

**Pull request closed without merging**
