### PR TITLE
[TS] LPS-89922

### PR DESCRIPTION
**Pull request by brianikim**
Resending with rebased PR from here: https://github.com/adolfopa/liferay-portal/pull/864

> Hello @adolfopa ,
> 
> https://issues.liferay.com/browse/LPS-89922
> 
> The issue here is that when you attempt to add document types past the maximum number of types allowed in the creation menu in Documents and Media, the remaining document types are suppose to be displayed by clicking the "More" button that appears. However, clicking the button does nothing because we completely lack the implementation for Documents and Media.
> 
> The solution is to implement the feature.
> 
> Commit: 458ed535aa4b967f92208fb023a881c807f94f69 implements the basic features required for the "More" button to work.
> Commit: 16cf3aa  implements a new search and filter method to handle not only keyword search of document types inside the More Menu frame, but also folder specific restriction checks to handle which document types should be displayed in the More Menu frame per folder. This is important because within each folder, you can restrict what document types can be added to the folder through Document Type Restrictions and Workflow setting when editing the folder.For your concern from the previous PR:
> 
> > I still don't understand why do we need to do further filtering on the document types. The inline permission helper should take care of that.
> 
> I have debugged to confirm that [inline permission helper](https://github.com/brianikim/liferay-portal/blob/LPS-89922/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFileEntryTypeFinderImpl.java#L339-L343) does not filter folder-specific document types.
> 
> Commit: 494d06c is straightforward. Search needs to be done on everything, but the result needs to reflect pagination.
> 
> Commit: a9aa12b and ea34d37  are improvements to the folder-specific restriction check to ensure that we are properly searching using parentFolder if inherited.
> 
> 
> Please let me know if you have any questions regarding the implementations.
> 

The source-formatter seen from https://github.com/adolfopa/liferay-portal/pull/864#issuecomment-470873199 is caused by this commit here: https://github.com/brianchandotcom/liferay-portal/pull/61274 as mentioned by @hhuijser. As he has mentioned on the email between us, please ignore the source format error if it is the same one as seen in https://github.com/adolfopa/liferay-portal/pull/864#issuecomment-470873199

> Go ahead and continue with that pull (you can comment on the ticket that I am working on the ticket and that's it's okay to ignore the failure for now).

cc/ @hhuijser

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hello @adolfopa ,

@hhuijser has submitted a fix for the source-format here: https://github.com/brianchandotcom/liferay-portal/pull/69499

If you find everything satisfactory with this PR other than the source-formatter issue, please send up the PR once @hhuijser 's commit has been merged to Master.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
hey @adolfopa ,

The issue is present even after @hhuijser 's submitted fix from https://issues.liferay.com/browse/LPS-92085

I have currently requested him to investigate the issue. I am not sure if you have reviewed the PR yet, but would you find it acceptable to send the PR up once the SF error has been resolved or do you find anything that should be improved the implementation?

Sincerely,
Brian Kim

**Comment by adolfopa** [comment]
@brianikim There is an issue with the "more" button (see https://github.com/ambrinchaudhary/liferay-portal/pull/216).

Regarding the filtering, I see you've removed it from this PR. I assume it works correctly now, so I've changed the impl. so that it uses paginated search and a new count method.

We'll send you the PR for review before pushing it to Brian.

Thanks!

**Comment by adolfopa** [comment]
Additionally, we need our UX people to review the change. D&M has some special cases that need to be taken into account, so this pattern may not be applicable as is.

We need to wait a couple of days (some of the people we need to talk to is on vacation until thursday), but we'll ping you when we have any news.

Thanks!

**Comment by brianikim** [comment]
Hello @adolfopa ,

Thank you for the follow-up. I will be waiting for your ping.

Sincerely,
Brian Kim

**Pull request closed without merging**
