### PR TITLE
LPS-96265 Remove hook.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Other than changing the name from repository.soap -> soap.repository, looks good. We'll send this when it doesn't interfere with the release.

**Pull request closed without merging**
