### PR TITLE
LPS-95290

### PR DESCRIPTION
**Pull request by samuelkong**
@arthurchan35

### CODE REVIEW

**Comment by samuelkong** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by arthurchan35** [comment]
@adolfopa 
It was not enough to fix the issue only with previous commits, because once client has cached files, the server will return a 304(not modified) to client next time client asks for the resource(files), so we have to do check before cache revalidation.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74282

**Pull request closed without merging**
