### PR TITLE
LPS-90231 Format icons and add tooltip in detail view

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
citr

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
@adolfopa we have a conflict in `modules/apps/document-library/document-library-api/bnd.bnd` can you check if is the right version

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86489.

**Pull request closed without merging**
