### PR TITLE
LPS-107521 Media gallery must support SVG

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@austinchiang wow, this sure got tested a lot... we need to stream line this..

Can you Slack me why this took so many retries before it was sent?

**Comment by austinchiang** [comment]
Contacted

**Pull request closed without merging**
