### PR TITLE
LPS-71658 The logic to check for a DL File's max allowable size is repeated in many places and should be replaced with a method

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-71658](https://issues.liferay.com/browse/LPS-71658).<br><br>/cc @pei-jung @xbrianlee

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by jpince** [comment]
failures unrelated. startTestableTomcat failure on an integration test happens from time to time. releaseversionstest failure is something bchan needs to fix, happens sometimes when he publishes.

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
closing to rebase and re-send.

**Comment by drewbrokke** [comment]
Resent as https://github.com/adolfopa/liferay-portal/pull/526

**Pull request closed without merging**
