### PR TITLE
LPS-108633 Add tests

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @adolfopa,

Take a look into this pull and if everything is ok, could you send it to @csierra?

Thanks!

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84635. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/f75efd5263e8~1...f75efd5263e8)

**Pull request closed without merging**
