### PR TITLE
LPS-95298 Build lang

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Hey @robertoDiaz 

I'm ok with these changes, but I won't send the pull to Brian until we finish the stabilisation phase.

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74232

**Pull request closed without merging**
