### PR TITLE
LPS-72933 Fix on ContactCenter Profile

### PR DESCRIPTION
**Pull request by mmariuzzo**
Hi Adolfo,

we have found two problems on Profile portlet. This code fix it

### CODE REVIEW

**Comment by adolfopa** [comment]
Hey @mmariuzzo 

Thanks a lot for your contribution. Could you add a brief description of the problem in a comment so that I can create a Jira ticket?

Thanks!

**Comment by mmariuzzo** [comment]
I've already create LPS-72933 in jira.

**Comment by adolfopa** [comment]
Oops, sorry. I didn't notice the LPS in the commit description.

Thanks!

**Comment by adolfopa** [comment]
Hey @mmariuzzo 
I've sent this to the User Mgmt. team, as this is not part of collaboration. I've made some changes (mainly refactoring the commit history). Please see https://github.com/drewbrokke/liferay-portal/pull/303

Thanks!

**Pull request closed without merging**
