### PR TITLE
LPS-71658 The logic to check for a DL File's max allowable size is repeated in many places and should be replaced with a method

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-71658](https://issues.liferay.com/browse/LPS-71658).

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:reopen

**Comment by xbrianlee** [comment]
ci:retest

**Comment by drewbrokke** [comment]
ci:retest

**Comment by xbrianlee** [comment]
There are Message Boards upgrade failures in the run above.
```
[java] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.document.library.kernel.exception.DirectoryNameException: messageboards/10583/10582
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:92)
     [java] 	at com.liferay.portal.upgrade.Pre7UpgradeProcess.upgrade(Pre7UpgradeProcess.java:42)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:175)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:143)
     [java] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:125)
     [java] 	at com.liferay.portal.events.StartupHelper.upgradeProcess(StartupHelper.java:164)
     [java] 	at com.liferay.portal.events.StartupHelperUtil.upgradeProcess(StartupHelperUtil.java:81)
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:153)
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:99)
     [java] Caused by: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.document.library.kernel.exception.DirectoryNameException: messageboards/10583/10582
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:92)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:116)
     [java] 	at com.liferay.portal.upgrade.UpgradeProcess_6_2_0.doUpgrade(UpgradeProcess_6_2_0.java:82)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:89)
     [java] 	... 8 more
     [java] Caused by: com.liferay.document.library.kernel.exception.DirectoryNameException: messageboards/10583/10582
     [java] 	at com.liferay.portlet.documentlibrary.store.DLStoreImpl.getFileNames(DLStoreImpl.java:330)
     [java] 	at com.liferay.document.library.kernel.store.DLStoreUtil.getFileNames(DLStoreUtil.java:424)
     [java] 	at com.liferay.portal.kernel.upgrade.v6_2_0.BaseUpgradeAttachments.getAttachments(BaseUpgradeAttachments.java:411)
     [java] 	at com.liferay.portal.kernel.upgrade.v6_2_0.BaseUpgradeAttachments.updateEntryAttachments(BaseUpgradeAttachments.java:604)
     [java] 	at com.liferay.portal.upgrade.v6_2_0.UpgradeMessageBoardsAttachments.updateAttachments(UpgradeMessageBoardsAttachments.java:88)
     [java] 	at com.liferay.portal.kernel.upgrade.v6_2_0.BaseUpgradeAttachments.doUpgrade(BaseUpgradeAttachments.java:402)
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:89)
     [java] 	... 11 more
```

**Comment by drewbrokke** [comment]
Closing to fix errors and resend.

**Comment by drewbrokke** [comment]
Resent as https://github.com/adolfopa/liferay-portal/pull/524.

**Pull request closed without merging**
