### PR TITLE
[TECHNICAL-SUPPORT] LPS-93348

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @jonathanmccann 

The bug is about the "Show Navigation" option, not the navigation bar itself.  So we should remove the option, but keep the navigation bar in admin (not in live).

After rereading the ticket, I see why you did this.  It is not entirely clear :-)

Sorry for the confusion!

**Comment by jonathanmccann** [comment]
@adolfopa Ah, that makes sense.

In that case should we still deprecate https://github.com/adolfopa/liferay-portal/pull/910/commits/f4aab3bf9ed786984a02e4475be2ece98a03dbd7#diff-2bbf56ea66fa12124c4d80476f1209f2R145 and then change https://github.com/adolfopa/liferay-portal/pull/910/commits/f4aab3bf9ed786984a02e4475be2ece98a03dbd7#diff-afc00ab7fb16f13219e2d711f7baf0b9R211 to return true only if we're on the admin portlet?

**Comment by adolfopa** [comment]
Yes, exactly that.

**Pull request closed without merging**
