### PR TITLE
[TECHNICAL-SUPPORT] LPS-88484

### PR DESCRIPTION
**Pull request by jonathanmccann**
@adolfopa I'm still not sure what performance issues your changes introduced but in the interest of time I wanted to push these changes up to see if this is what you were looking for.

Please let me know if you have any questions or if this introduces the same regression as the previous fix.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by joshchong** [comment]
ci:test

**Comment by joshchong** [comment]
FYI running ci:test since the tests that caught the regressions don't run on ci:test:relevant.

**Comment by adolfopa** [comment]
@jonathanmccann My changes didn't introduce a performance problem, but a regression (different behaviour). What I was referring to was a *potential* performance problem while trying to implement that again with one single query (and no IN clauses).  I needed a custom query that was way too complicated (and slow). So, that's why I think it is better to keep things simple and keep using IN, but limiting its size so that we don't hit any reasonable limit.

Sorry for the misunderstanding :-)

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66171

**Comment by jonathanmccann** [comment]
Thanks for the explanation!

**Pull request closed without merging**
