### PR TITLE
LPS-85890 Message boards show empty value for thread replies of deleted users

### PR DESCRIPTION
**Pull request by hudakl**
Hi Adolfo,

Please find my solution propsal for LPS-85890.
Could you please review my changes?

Thanks,
Laci

### CODE REVIEW

**Comment by adolfopa** [comment]
Hey @hudakl 

The method `getLastPostByUserId` is used in a handful of places. We should check those as well to make sure the same user info is displayed everywhere.

Also, updating only the portlet views may not be the best solution. Other users of the API (e.g. REST, JSONWS, etc.) will get the wrong data unless we put the fix at a lower lever.  I think overriding the `MBThread.getLastPostByUserId` and `MBThread.getLastPostByUserUuid` is better (at least we cover more cases).

Thanks!

**Comment by hudakl** [comment]
Hi @adolfopa ,

I'm a bit confused by your answer. I don't fully understand why and how we should override the MBThread.getLastPostByUserId and the MBThread.getLastPostByUserUuid.

I checked the Message Boards code, but I didn't find any other part where it could lead to such problems. I changed the view because the problem presented itself on the UI. The issue occurs simply because we get the userId of the last message on a thread with the MBThread.getLastPostByUserId method, then we want to get the user name from the users_ table based on the id. Since the there's no user belonging to the id anymore, we get nothing back. But because we store the user name in the message itself, we can just get the last message and get the user name from the post.

The problem is not with the MBThread.getLastPostByUserId method. It returns the data it supposed to, it was merely used wrongly in this part of the portlet. So I don't really know what else should I have done differently. Could you please elaborate on what you had in mind?

Thank you in advance for your reply,
Laci

**Comment by hudakl** [comment]
Hi @adolfopa,

Do you have any updates on this pull in light of my previous comment?

Thanks,
Laci

**Comment by adolfopa** [comment]
Sorry @hudakl, I missed the notification for your reply.

You're right. I thought that, when the last user was missing, you were trying to display the information of the latest valid user. But your approach is correct. I'm sorry about the misunderstanding.

Could you resend the changes to me?

Thanks!

**Pull request closed without merging**
