### PR TITLE
LPS-96426 Users see sites listed in Item Selector where they have no VIEW access to the Site's root document folder

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @adolfopa,

Could you please review this pull request?

I added a permission check which checks if the current user has VIEW permission to the Site's Documents and Media Home folder.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @IstvanD 

The check cannot be added in the group selector.  Technically, the item selector can be used for things other than documents (e.g. layout selection), and adding the permission check here would break all other use cases.

Also, this is not really a bug, as the group selection is independent of the context by design; As the customer is asking for a change of behaviour, could you open a Feature Request for this?  We'd need to extend the API so that additional item filtering can be provided depending on the context.

I'll close the bug ticket as won't fix.

Thanks!

**Comment by IstvanD** [comment]
Hey @adolfopa 

Thank you for the feedback.

The customer really has two complaints about the current behavior.

The first, which this fix solves, is that a user it able to select a Site in Item Selector even if they have no view permission for the home folder of the Site's Document Library.

The second is that a user can select **private** Sites in the Item Selector where they are **not a member** of. According to the customer, it the user is not member of the private Site, they shouldn't be able to see it in the Item Selector.

Could you please tell me what you think about this second scenario?
It this behavior a bug or not?
Should I open a PTR to raise this question?

Thank you and best regards,
István

**Comment by adolfopa** [comment]
Yes, this second scenario is definitely a bug.

**Comment by IstvanD** [comment]
Hey @adolfopa 

There is no LPS for it, but I'll open one.

Thanks and best regards,
István

**Pull request closed without merging**
