### PR TITLE
LPS-107215 Check for vocabularies in for other file entry types.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/ealonso/liferay-portal/pull/2704

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83512

**Pull request closed without merging**
