### PR TITLE
LPS-137889 Additional commits

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi @adolfopa, as requested in https://github.com/brianchandotcom/liferay-portal/pull/106632 by Brian I've included an extra commit for LPS-137889 where I sort the mockings according to the rest of the logic. Please let me know if you consider its not enough.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Pull request closed without merging**
