### PR TITLE
LPS-104840 generate ddmStructure on startup

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81369. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/2c2bfd7f191c~7...2c2bfd7f191c)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81370. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/559c9daec631~7...559c9daec631)

**Pull request closed without merging**
