### PR TITLE
LPS-72803 Do not append the origin for links to wiki pages in AlloyEditor

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by ambrinchaudhary** [comment]
@adolfopa hay errores de semantic versioning. Te encargas tú de corregirlos por favor?

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/49381

**Pull request closed without merging**
