### PR TITLE
LPS-104702 ant build-lib-versions

### PR DESCRIPTION
**Pull request by JavierMoral**
Hi,
[LPS-104702](https://issues.liferay.com/browse/LPS-104702)
Could you please take a look at this?
Thanks!
cc @robertoDiaz

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by JavierMoral** [comment]
ci:test:documents

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81252.

**Pull request closed without merging**
