### PR TITLE
LPS-102706 Delete the corresponding expando rows as well upon deleting the MBMessages

### PR DESCRIPTION
**Pull request by hudakl**
Hi,

Could you please review my changes for LPS-102706.

Thanks,
Laci

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Hey @hudakl 

I'm ok with the changes, but could you add a test?

Thanks!

**Comment by hudakl** [comment]
Hi,

I'll see what I can do.

Thanks,
Laci

**Comment by adolfopa** [comment]
Thanks @hudakl. I'm closing this pull in the meantime.

**Pull request closed without merging**
