### PR TITLE
[TS] LPS-98556 Incorrect classname is used for journal article subscriptions after upgrading to 7.1

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-98556

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See https://github.com/ealonso/liferay-portal/pull/2480.

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
