### PR TITLE
[TS] LPS-113276

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/38. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/d2c1116f3d7d~6...d2c1116f3d7d)

**Comment by adolfopa** [comment]
Hey @jonathanmccann 

Can you send any future PRs to the "liferay-lima" user?

Thanks!

**Comment by jonathanmccann** [comment]
Of course, thank you for letting me know.

**Pull request closed without merging**
