### PR TITLE
LPS-108720 see on customizer if selector is instanceof PortletItemSelectorView and check if is enabled

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84811. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/4a695c171169~3...4a695c171169)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84820. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/ddb50db38f1c~4...ddb50db38f1c)

**Pull request closed without merging**
