### PR TITLE
LPS-109257 check asset library enable to show panel

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85413. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/243db75d5e16~5...243db75d5e16)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85443. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/96e3560e77cf~5...96e3560e77cf)

**Pull request closed without merging**
