### PR TITLE
Lps 109346 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Hello @adolfopa,

https://issues.liferay.com/browse/LPS-109346

This pull fixes an issue when upgrading the SO_MemberRequest table to IM_MemberRequest table in the invite members module. Initially when this upgrade was created, the MemberRequestTable.java class was not created correctly and left on IM_ from the table name. Post upgrade this leads to issues since the table cannot be found. Additionally, the table name is not always changed, if there is data, the table will be renamed, if there is no data, it will remain the same.

/cc @achaparro

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/85403.

**Pull request closed without merging**
