### PR TITLE
LPS-72729 Since AssetEntryException is not serializable, it could not be used with the @Test(expected) annotation, we could use this hack to assert that this exception is been thown.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @linolaoj 

I've finally found a way to fix this in a more extensible way.

Test was fine, just a little SF 👍. I've also add more test cases.

Thanks!!!

**Comment by robertoDiaz** [comment]
ci:retest

**Comment by robertoDiaz** [comment]
All Right!!

👍

**Comment by adolfopa** [comment]
See https://github.com/robertoDiaz/liferay-portal/pull/568

**Pull request closed without merging**
