### PR TITLE
[TS] LPS-89922

### PR DESCRIPTION
**Pull request by brianikim**
Resending with rebased PR from here: https://github.com/adolfopa/liferay-portal/pull/857

> Hello @adolfopa ,
> 
> https://issues.liferay.com/browse/LPS-89922
> 
> The issue here is that when you attempt to add document types past the maximum number of types allowed in the creation menu in Documents and Media, the remaining document types are suppose to be displayed by clicking the "More" button that appears. However, clicking the button does nothing because we completely lack the implementation for Documents and Media.
> 
> The solution is to implement the feature.
> 
> Commit: 5d825928e0be017de83d7375688bf209dfaed470 implements the basic features required for the "More" button to work.
> Commit: 15eb305d25f68cea3fbcebff65a6508f5cbde56e implements a new search and filter method to handle not only keyword search of document types inside the More Menu frame, but also folder specific restriction checks to handle which document types should be displayed in the More Menu frame per folder. This is important because within each folder, you can restrict what document types can be added to the folder through Document Type Restrictions and Workflow setting when editing the folder.For your concern from the previous PR:
> 
> > I still don't understand why do we need to do further filtering on the document types. The inline permission helper should take care of that.
> 
> I have debugged to confirm that [inline permission helper](https://github.com/brianikim/liferay-portal/blob/1c44cd061a6f5ea90bbc4192a445b1d4d57b1b8c/portal-impl/src/com/liferay/portlet/documentlibrary/service/persistence/impl/DLFileEntryTypeFinderImpl.java#L339-L343) does not filter folder-specific document types.
> 
> Commit: e99eb17 is straightforward. Search needs to be done on everything, but the result needs to reflect pagination.
> 
> Commit: f1a2e6c and 1c44cd0 are improvements to the folder-specific restriction check to ensure that we are properly searching using parentFolder if inherited.
> 
> 
> Please let me know if you have any questions regarding the implementations.
> 

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @adolfopa ,

The unique failure does not seem related.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
Hello @adolfopa ,

If you find the review satisfactory, please send up the PR when you are available. I will be out on PTO (March 8th). If you require any changes, you can reassign the ticket back to me and I will work towards resolving the issue next Monday when I am back.

Sincerely,
Brian Kim

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
@brianikim There are some SF errors (see ci:test:sf results in this same PR); I can reproduce them locally running `ant format-source`.

**Comment by brianikim** [comment]
Hello @adolfopa ,

Just as a quick update, the source-formatter issue is caused by the change from this commit: https://github.com/brianchandotcom/liferay-portal/pull/61274

Note that the source-formatter is working incorrectly here as opposed to a source format issue in this PR.

I am currently working with the engineer to fix the source-format behavior and will be resending you a PR for this after.

Sincerely,
Brian Kim

**Pull request closed without merging**
