### PR TITLE
pull-request-28249

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/28249

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/105. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/8aabb8f~4...8aabb8f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/28326. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/a9a7b0d~5...a9a7b0d) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
