### PR TITLE
LPS-104547

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/adolfopa/liferay-portal/pull/1158

See https://issues.liferay.com/browse/LPS-104547 for issue description.

Fix is to pass in the status of the fileEntry so that the add button can be disabled if status is not approved.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Hey @brianikim 

Sadly, we cannot assume that only approved items are the only valid ones. In the case of journal (which uses the item selector as well), non approved items need to be selected as well. The changes in ItemSelectorDialog.es.js prevent this from working.

Maybe we should provide a means of telling item selector which states are valid. Then ItemSelectorDialog would be able to check if the state is contained in the accepted ones, and not only check if it is approved.

Thanks!

**Comment by brianikim** [comment]
Hello @adolfopa ,

I have to disagree with you here. Non-approved content (content being fileEntry, journalArticle, etc.) here means any content that is not STATUS_APPROVED = 0. This includes pending/draft contents as well. Regardless of my changes being implemented here, item selector will not show any content that does not have status = 0. Liferay has a consistent behavior across all components using item selector as its method of selecting files/contents in which non-approved contents cannot even be searched for/seen/selected for in item selector. Therefore, I am having a bit of difficult understanding your point regarding "non approved items need to be selected as well."

Please let me know if my understanding of the issue needs to be further tweaked.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
ci:reopen

**Comment by adolfopa** [comment]
@brianikim In the case of journal (only in the JournalContent portlet config), the ability to select a non approved element is a business requirement. It is true that in all other cases, only approved items should be selectable, but we have to take into account Journal's special case.

@ealonso Can we safely exclude articles that are in workflow? If displaying approved and scheduled entries is enough, we could fix the query used in WC so that it ignores any other states.

Thanks!

**Comment by brianikim** [comment]
Hello @adolfopa , @ealonso ,

Please let me know once you guys reach a final decision on how to address the business requirement/use-case.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
Hello @adolfopa , @ealonso ,

Would it be alright if I revised this PR and made the feature a system configuration instead?

Sincerely,
Brian Kim

**Comment by ealonso** [comment]
Hey @brianikim,

We are using the Item Selector on Web Content Display. So related to it, we need to have the ability of selecting non-approval Web Content, since this is our business use case. We allow approved web content and scheduled web content.

Regards,
Eudaldo.

cc: @adolfopa

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @adolfopa  and @ealonso ,

I have added the requirements you have requested. The implementation will now consider both approved and scheduled contents.

Note that you guys will have to fix your query for the searchcontainer so that scheduled web contents are listed as well as you have explained earlier.

I will be out on PTO all of next week.

Sincerely,
Brian I. Kim

**Comment by adolfopa** [comment]
@brianikim We're working on fixing some other Journal Item Selector regressions that should cover this case. I'll keep this PR working until everything is fixed.

**Comment by brianikim** [comment]
Thank you @adolfopa ,

Please let me know once the changes are introduced.

Sincerely,
Brian I. Kim

**Comment by brianikim** [comment]
Hello @adolfopa ,

Is there any update on your progress? I do require an update as the ticket is tied to a LPP.

**Comment by adolfopa** [comment]
A fix has been merged in master.

**Pull request closed without merging**
