### PR TITLE
[TECHNICAL SUPPORT] LPS-88762

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-88762

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi @adolfopa 

Do you have any update about this PR?

Thank you

**Comment by adolfopa** [comment]
Sorry for the delay. This week we've had some events (candidate interviews, Brian's visit, etc.) that have taken most of our time. I'll try to review this today, or, in the worst case, tomorrow.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/66859

**Comment by jorgediaz-lr** [comment]
Thank you, @adolfopa

**Pull request closed without merging**
