### PR TITLE
LPS-106977 Autogenerated

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1209. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/6dfbdc91a3f5~8...6dfbdc91a3f5)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83323. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/6dfbdc91a3f5~8...6dfbdc91a3f5)

**Pull request closed without merging**
