### PR TITLE
LPS-92335 portal-search-test-util: Update BaseSearchTestCase

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-92335

Related to https://github.com/adolfopa/liferay-portal/pull/881

/cc @BryanEngler

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:search

**Comment by adolfopa** [comment]
@lipusz Do you know why the search tests won't run? Do I need to do anything special to the configuration that other CI commands don't need?

**Comment by lipusz** [comment]
@xbrianlee @ joshchong Do you know why ci:test:search does not run?

**Comment by adolfopa** [comment]
They run fine on Brian's queue. See https://github.com/brianchandotcom/liferay-portal/pull/69724

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
now it works here too. :-)

**Pull request closed without merging**
