### PR TITLE
LPS-87496 Folder permissions are not inherited

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hey @robertoDiaz 

Could you please review this pull request?

I added the option for the DL subfolders to inherit their parent folder's permission, when they are created. The permission of the subfolders can be changed at any time afterwards.

I wanted to add the option as a module configuration, but then I saw that the file, `DLFolderLocalServiceImpl.java`, where the logic of the folder creation resides is in portal-impl.
Therefore, I added the property `dl.folder.inherit.permissions`.

However, I also added the configuration option `inherit-folder-permissions` to `DLConfiguration` in advance in case `DLFolderLocalServiceImpl.java` is moved to the document-library-service module.

Please let me know what you think of this solution.

Can it be released to the customer as an SDH?

Thank you and best regards,
István

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @adolfopa 

Can you tell us:

1. Is this a bug in previous releases (7.0 and 7.1) or a limitation?
2. This log is compatible with the behavior we would like to introduce in the future??

Thanks!!

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @robertoDiaz @IstvanD

We have a story that should cover this use case (see https://issues.liferay.com/browse/LPS-85894), so I'd prefer to wait and develop the whole thing when we got the time. Sadly, I don't think this will make it into 7.2, we have a lot of other stuff in our hands atm.

About this being a bug, I see it as the expected behaviour. We have a related feature (dynamic inheritance), which propagates the VIEW permission as long as the `permissions.view.dynamic.inheritance` property is enabled. AFAIK, it was never the intention for this to support other actions than VIEW.

**Comment by adolfopa** [comment]
Still in conversations with PM regarding introducing this feature.

**Comment by adolfopa** [comment]
We'll implement this as part of the story linked in the comments.

**Pull request closed without merging**
