### PR TITLE
LPS-110524 SF

### PR DESCRIPTION
**Pull request by LuismiBarcos**

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1362. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/fb63d792d542~1...fb63d792d542)

**Pull request closed without merging**
