### PR TITLE
LPS-107941 Move code to displayContext

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84066. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/eff0e7e6901e~2...eff0e7e6901e)

**Pull request closed without merging**
