### PR TITLE
LPS-55021 Create reusable module for control panel

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
@adolfopa Please update your PR. We need to review: 
* Replace current togglerComponentId for the user panel "_com_liferay_productivity_center_portlet_ProductivityCenterPortlet_userPersonalPanelMenuAddContentPanelContainer"
* User panel is checking the attribute "control-panel-sidebar-minimized", that is why it gets his minimized status. We should now listen a new attribute called "user-panel-sidebar-minimized"

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/159. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
