### PR TITLE
[TS] LPS-107145

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-107145

From @wanderlast:

> So the issue is that when a user uploads a PDF, logging appears for each PDF that does not appear to be related. Specifically, it'll be similar to:
> 
> ```
> Loading jar:file:/home/matt/repos/lfrgs-liferay-damage-control/build/exported-standalone-bundle/tomcat/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/system.properties
>  Jan 15, 2020 11:10:51 AM com.liferay.portal.kernel.log.Jdk14LogImpl info
>  INFO: Detected server tomcat
>  [dxp] INFO [main][PropsUtil:385] Global shared lib directory /home/matt/repos/lfrgs-liferay-damage-control/build/exported-standalone-bundle/tomcat/lib/
>  [dxp] INFO [main][PropsUtil:396] Global lib directory /home/matt/repos/lfrgs-liferay-damage-control/build/exported-standalone-bundle/tomcat/lib/ext/
>  [dxp] INFO [main][PropsUtil:419] Portal lib directory /home/matt/repos/lfrgs-liferay-damage-control/build/exported-standalone-bundle/tomcat/webapps/ROOT/WEB-INF/lib/
>  Loading jar:file:/home/matt/repos/lfrgs-liferay-damage-control/build/exported-standalone-bundle/tomcat/webapps/ROOT/WEB-INF/lib/portal-impl.jar!/portal.properties
> ```
> 
> The cause of this logging can be traced back to PDFProcessorImpl. Specifically, if the DL_FILE_ENTRY_PREVIEW_FORK_PROCESS_ENABLED property is enabled, we fork our process which causes certain lines of logging to appear when the classes are accessed again in this new forked process. The fix reduces the logging, but does not completely eliminate it. Specifically, it passes on custom log settings to remove the **PropsUtil** log messages. The other log messages do not appear to be removable without extensive effort (e.g. completely disabling logging), so they have not been addressed.
> 
> Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84665. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/10c2b005ed76~2...10c2b005ed76)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84845. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/e7f2d21d144c~4...e7f2d21d144c)

**Pull request closed without merging**
