### PR TITLE
LPS-67467

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/43732

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/355. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/5575165~2...5575165) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/43827. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/5575165~2...5575165) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
