### PR TITLE
LPS-54159 Reuse same instance for all types

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
https://github.com/sergiogonzalez/liferay-portal/commit/b542d6197ebb5db9dfbe9a337443180b2eb30dd2 : Falta por sacar una comprobación de permisos.
https://github.com/sergiogonzalez/liferay-portal/commit/8a9514972eb2d51c70db45284cc646e70c1e2ed0: confirmar que se puede obtener layoutTypePortlet y plid desde el layout?

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2044. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/d60193c~10...d60193c) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/2050. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/b7bd9780~12...b7bd9780) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
