### PR TITLE
[NOT TO MERGE] LPS-90404 versions

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Manual changes on versions files like on LPS-88839.
build-lib-versions remove the updated entries and make things that don't fit with the dependencies.properties file

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:staging

**Comment by AliciaGarciaGarcia** [comment]
ci:test

**Pull request closed without merging**
