### PR TITLE
LPS-111598 Make pending comment visible to the content reviewer

### PR DESCRIPTION
**Pull request by rafaprax**
From @IstvanD:

> I enabled Content Reviewers to see pending comments. However, they now also see the Action menu of the comments, so they can Edit and Delete them without assigning the reviewing task to themselves. Normally, then can only do that after opening their review notifications and assigning the task to themselves.
>
>Is this something that has to be dealt with in this solution?
>
>Thank you and best regards,
>István

Thx

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@IstvanD it seems content reviewers always have update permissions (see WorkflowPermissionImpl around line 57).

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
