### PR TITLE
LPS-105112 move custom_tags and logic to layout-seo-web module

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:lima

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1182. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/17661877b4ca~4...17661877b4ca)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81706. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/187d38d5206a~7...187d38d5206a)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81862. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/435e047eb419~7...435e047eb419)

**Pull request closed without merging**
