### PR TITLE
LPS-104923 Uses new methods

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81372. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/7b670349267f~2...7b670349267f)

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/81372

**Pull request closed without merging**
