### PR TITLE
LPS-104630 Move CSS also

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81247. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/e349ad8a9f8a~8...e349ad8a9f8a)

**Pull request closed without merging**
