### PR TITLE
LPS-111494 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
@austinchiang Still flaky :-(

**Comment by austinchiang** [comment]
This will be tracked in https://issues.liferay.com/browse/LRQA-57964

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
one more time for good measure

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
