### PR TITLE
LPS-97094 User's Personal Data is not fully anonymized in Related Assets

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Adolfo,

Can you take a look at this and see if the changes look good to you? When updating the user fields (userId and userName) of a blog entry, its related asset entry does not get updated. `BlogsEntryLocalService.updateAsset` doesn't update the user fields of the asset entries so we have to update it manually.

This also affects DM, Message Boards, and Wiki. If all looks good, we'll apply the changes to the other entites. Thanks\!

### CODE REVIEW

**Comment by adolfopa** [comment]
Hey @pei-jung 

Sorry for the delay.  Is there any reason you didn't add this logic to the autogenerated?

In theory, it is possible to check if a model supports assets in a generic way (by checking if it has an AssetRendererFactory); we could add that to the templates, and run some extra logic to update the asset if the model supports assets.

Do you think it is worth a try? If you're ok, I can give it a try and send you a pull with the changes.

Thanks!

**Comment by pei-jung** [comment]
Hi @adolfopa,

That's actually our first approach when trying to fix this issue. However, there's a couple concern that we had when trying to do this in a generic way. Please see https://github.com/pei-jung/liferay-portal/pull/459. Thanks!

**Comment by adolfopa** [comment]
See my comment in https://github.com/pei-jung/liferay-portal/pull/459

Thanks!

**Pull request closed without merging**
