### PR TITLE
Lps 71504 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
Hi Adolfo, did you have a chance to look at my comment after you closed pull request: https://github.com/adolfopa/liferay-portal/pull/495

I also sent the pull request:
https://github.com/4lejandrito/liferay-portal/pull/31
 to Alejandro since customer is still waiting.

Thanks

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by brianwulbern** [comment]
ci:retest

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/48384

**Pull request closed without merging**
