### PR TITLE
LPS-67287

### PR DESCRIPTION
**Pull request by daledotshan**

### CODE REVIEW

**Comment by daledotshan** [comment]
Information from Hai

Information from Hai

The issue extends from juliocamarero#4193 (comment)

The main issue is LPS-67287. LPS-67287 root issue is that the attachment shouldn't create a TrashEntry when the thread is moved to the recycle bin. Julio had confirmed the behavior is wrong. Please refer to juliocamarero#4193 (comment)

What issue caused LPS-67287? Please refer to the below explanation:
Explanation: 
juliocamarero#4193 (comment)

LPS-67287 mainly finish we shouldn't add dlFileEntey (attachment) data into trashEntry table when move MBthread with attachment to the recycle bin. Please refer to the below logic:

Move to trash:
MBThreadLocalServiceImpl.moveDependentsToTrash()->PortletFileRepositoryUtil.movePortletFileEntryToTrash()->...->DLAppHelperLocalServiceImpl.doMoveFileEntryToTrash()

Restore from trash: 
MBThreadLocalServiceImpl.restoreDependentsFromTrash()->PortletFileRepositoryUtil.restorePortletFileEntryFromTrash()->..->DLAppHelperLocalServiceImpl.restoreFileEntryFromTrash()

LPS-67404: Because LPS-67287 changes restoreFileEntryFromTrash(), so we need to firstly solve the issue.
When restore MBthread with attachment from Recycle Bin, we should use getDeletedAttachmentsFileEntries() because its status is 8 so that we can fetch dlfileEntry(status:8).

**Comment by daledotshan** [comment]
Hey Adolfo,
Sergio is on vacation so I sent this pull request to you, could you help to review this ticket as high priority since it is a for a ee customer

Thanks,
Dale

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/42166. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/1daa650~1...1daa650) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
