### PR TITLE
[TS] LPS-103774

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPP-35469
https://issues.liferay.com/browse/LPS-103774

From @wanderlast 

> Currently, due to changes introduced in [LPS-86455](https://issues.liferay.com/browse/LPS-86455), we no longer continuously attempt to regenerate a preview upon the failure of preview generation (typically due to something like an encrypted PDF that could not be decrypted). This change can be seen in https://github.com/liferay/liferay-portal/commit/dfdb0adc703f24fc63b427bf867bfc13f5c4b603. Knowing this, it seems inconsistent that we still continuously attempt to generate metadata, considering that this leads to the same EncryptedDocumentExceptions that one would see if we tried to regenerate a preview. This fix stops generation of metadata if a preview has failed to generate.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80469.

**Pull request closed without merging**
