### PR TITLE
LPS-101158 Change literal and delete unused.

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80188. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/678ab7ca3818~5...678ab7ca3818)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80201. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/95998ff18a70~6...95998ff18a70)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80226. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/09f4b22d2330~6...09f4b22d2330)

**Pull request closed without merging**
