### PR TITLE
LPS-109952 add view site administration for asset libraries on the same cases than in sites.

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86326. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/5c57bcff506a~2...5c57bcff506a)

**Pull request closed without merging**
