### PR TITLE
LPS-103335 The template handler is used by the Media Gallery and not the D&M portlet

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by hudakl** [comment]
Hi @adolfopa ,

Do you have any updates on the review?

Thank you,
Laci

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83746. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/03fdad6e0ffc~2...03fdad6e0ffc)

**Pull request closed without merging**
