### PR TITLE
LPS-91295 Support default autotagging for Journal.

### PR DESCRIPTION
**Pull request by cgoncas**

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:reopen

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/71026

**Pull request closed without merging**
