### PR TITLE
LPS-108921 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/ambrinchaudhary/liferay-portal/pull/312. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/23f7487d758d~3...23f7487d758d)

**Pull request closed without merging**
