### PR TITLE
LPS-73070 Creates package-lock files (auto-generated)

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:retest

**Comment by jbalsas** [comment]
Hey @ithildir, can you take a look at this?

**Comment by Ithildir** [comment]
I think the problem is that `gulp-metal` has a dependency on `node-sass`, so `npmInstall` tries to download `https://github.com/sass/node-sass/releases/download/v3.13.1/linux-ia32-57_binding.node`, which doesn't exist. Then it tries to compile locally, but the compilation fails. Have a look at around line 5300 of https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-dist(master)/AXIS_VARIABLE=tomcat,label_exp=!master/1643/consoleText.

**Comment by jbalsas** [comment]
Resent to https://github.com/adolfopa/liferay-portal/pull/623

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/627. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/93bf89c28e8d~1...93bf89c28e8d)

**Comment by jbalsas** [comment]
Guay, te costó un tiempo, pero ya parece que lo tienes! 💪

**Pull request closed without merging**
