### PR TITLE
LPS-69952

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Hey @daledotshan 

I'm not able to reproduce the problem on current master following the instructions in the issue. Could you please recheck?

Thanks!

**Comment by daledotshan** [comment]
Hey @adolfopa 
You are right this issue does not happen anymore after since master include a fix LPS-23146

**Comment by daledotshan** [comment]
I did further investigating about this issue actually 6.2.x already include the fix LPS-29962 but because one one engineer commit specific fix https://issues.liferay.com/browse/LPS-68931 for 6.2.x cause the issue happen

**Comment by adolfopa** [comment]
Thanks @daledotshan!

@robertoDiaz If I recall correctly, LPS-68931 had a big (in a good sense) impact on performance. Is it worth forward-porting that to master? If that's the case, I'll need to merge this PR also.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3718. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/7fcf0ff~1...7fcf0ff) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sergiogonzalez/liferay-portal/pull/3719. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
See https://github.com/sergiogonzalez/liferay-portal/pull/3719

**Pull request closed without merging**
