### PR TITLE
LPS-68460

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @adolfopa,

I'm forwarding you this so you can keep track of it.

As we discussed, the fix should be applied on the Message Boards App, so this fix should be removed for a more specific one.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by BryanEngler** [comment]
sounds good, thanks for the info! ill create a ticket and also look to see if there are any other places where we can find the issue.

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44183. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/f818f19~1...f818f19) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
