### PR TITLE
LPS-71509 Do not append "http://" protocol to the links created with AlloyEditor

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc @sergiogonzalez

**Comment by ambrinchaudhary** [comment]
Will send a new PR because the last commit is not clear yet

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/495. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/be28043e6e07~1...be28043e6e07)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/498. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/b2bdc4c87734~1...b2bdc4c87734)

**Pull request closed without merging**
