### PR TITLE
LRQA-21159 Fix tests to assert new sidebar panel details in DM portlet

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:retest

**Comment by adolfopa** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@adolfopa investigating failures, I'll try to push you a fix soon! sorry for the delay!

**Comment by adolfopa** [comment]
Thanks a lot @sharonchoi. See https://github.com/brianchandotcom/liferay-portal/pull/34745

**Pull request closed without merging**
