### PR TITLE
LPS-103091 Avoid truncating in the middle of an encoded characters taking into account surrogate pairs

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-103091

Hi @adolfopa  ,

Can you help review the following fix? Feel free to let me know if this should be reviewed by another reviewer.

Issue: The current logic for truncating the urlTitle does not properly account for surrogate pairs.

For additional context, please see: https://issues.liferay.com/browse/PTR-1224?focusedCommentId=1969372#comment-1969372

/cc @dacousalr

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by ericyanLr** [comment]
Hi @adolfopa ,

When you get a chance, can you provide an update for this pr?
Thanks!

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80374. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/eb1ea5904216~6...eb1ea5904216)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/80375. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/98ef97c9c7c8~5...98ef97c9c7c8)

**Pull request closed without merging**
