### PR TITLE
LPS-69255

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@sergiogonzalez @adolfopa see questions here as it pertains to Blogs as well.

1.) UpgradeMVCCVersion is usually called by UpgradeSchema.

See com.liferay.portal.upgrade.v6_2_0.UpgradeSchema

2.) Since we have upgrade code for this in 7.0.3, does this mean we mean we will backport this? And what about blogs? Do we need to backport the blogs modularization?

3.) I don't see SubscriptionModelAdapterBuilder used in Blogs?

4.) See modules/core/portal-compat/blogs

We use this pattern to rip out code to ensure 100% backwards compat.

Please resend? Thx.

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/462. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/0e45d1f~2...0e45d1f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46640. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/b756c86~2...b756c86) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46752. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/be81ff2~2...be81ff2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46792. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/36be4bf~2...36be4bf) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46835. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/a4c6b5b~4...a4c6b5b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/46845. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/1ab8f94~4...1ab8f94) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
