### PR TITLE
LPS-105652 Semver

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
I think the issue is the bump in the [json packageinfo](https://github.com/adolfopa/liferay-portal/pull/1426/commits/bcdf4e040edece70c45c157f3e25d9a76b50d8a0#diff-8ad5c341370b1a9c746e519cef1c4488R1). I removed that change and resent the pull here: https://github.com/liferay-lima/liferay-portal/pull/17

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/21

**Pull request closed without merging**
