### PR TITLE
[TS] LPS-110699

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1341.

**Comment by jpince** [comment]
ci:forward

**Comment by jpince** [comment]
@adolfopa for next time, if you don't have any changes, you can just run `ci:forward` on this pull, no need to create a new one to yourself. This will save time and CI resources :)

[See this Google Doc for more info](https://docs.google.com/document/d/1GrDg82MCAoPNMQJPYpG5e3ZGev4gxVaobfqyO9-rY2Y/edit#heading=h.7n8dmerkdbk9)
> If the tests pass, the reviewer can comment “ci:forward” and the commits will be sent directly to BChan without further testing

**Pull request closed without merging**
