### PR TITLE
[TECHNICAL-SUPPORT] LPS-102022

### PR DESCRIPTION
**Pull request by jonathanmccann**
@adolfopa,

The "Question" display style is used to force all threads created within it to be marked as a question. This change adds a question mark icon to the side of the category name much like question threads:

https://github.com/liferay/liferay-portal/blob/master/modules/apps/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/view_thread_entries.jspf#L81-L83

If you'd rather remove this question style altogether let me know but that will be a larger change requiring an upgrade process to convert question style categories to default.

Thanks.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/79341. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/0b06c0982a95~1...0b06c0982a95)

**Pull request closed without merging**
