### PR TITLE
LPS-96116 Update references

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Should be fixed by 12cbd0f9b7e070e36d41928f8a97b4ac518bf9bc

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
