### PR TITLE
LPS-96564 Users see private Sites listed in Item Selector where they are not a member of

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @adolfopa 

Could you please review this pull request?

As it was stated in https://github.com/adolfopa/liferay-portal/pull/998#issuecomment-499782954, [LPS-96564](https://issues.liferay.com/browse/LPS-96564) is a bug that needs to be fixed.

I added exclusion for those private Sites whom the current User is not a member of.

Thank you and best regards,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74286

**Comment by IstvanD** [comment]
Hey @adolfopa 

I have tested the fix with your modifications.
Unfortunately, now every Site where the User is not a member of are filtered out, not just the private ones.
This is because [this part of the code](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/permission/GroupPermissionImpl.java#L204-L205) checks only for membership, and doesn't takes account whether the Site is private or not.

Please let me know if we can deal with this in this LPS or we should open another.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hey @adolfopa 

I would like to kindly ask if you could find the time to read my last comment.

Please feel free to share your thought.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
Hey @IstvanD 

I think this should be fixed in the Group permission logic.  I'll send a pull to WEM, so that a group is visible if `isMember() || group.isPublic()`.

Thanks!

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/ealonso/liferay-portal/pull/2422

**Comment by IstvanD** [comment]
Hey @adolfopa 

Many thanks for dealing with it and sending the pull to @ealonso !

Best regards,
István

**Pull request closed without merging**
