### PR TITLE
Using a dynamic query to get only the relevant permissions from the database

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by 4lejandrito** [comment]
ci:retest

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/4lejandrito/liferay-portal/pull/13. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/96c7701~3...96c7701) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/44675. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/96c7701~3...96c7701) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
