### PR TITLE
[TS] LPS-91413

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-91413

Deals with the prevention of rendering a "View in Context" link when it would generate a 404.

CC @jrao

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jrao** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Sorry for the delay guys. See https://github.com/brianchandotcom/liferay-portal/pull/69733

**Pull request closed without merging**
