### PR TITLE
LPS-131274 Take showActions option into account when displaying add button in DM portlet instances.

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
Hi @adolfopa, did you have the time to review this?
Thanks! :)

**Comment by adolfopa** [comment]
ci:forward

**Comment by crodriguezy** [comment]
Hi @adolfopa , would it make sense to add an extra commit here to fix the affected functional tests?

**Comment by adolfopa** [comment]
Yes, I think it makes sense to send everything together. @austinchiang?

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by Hanlf** [comment]
Resend it with the test fix under https://github.com/liferay-lima/liferay-portal/pull/1792

**Comment by Hanlf** [comment]
ci:close

**Pull request closed without merging**
