### PR TITLE
LPS-96304 When the user is ContentReviewer, we may use localServiceUtil to avoid the permission check.

### PR DESCRIPTION
**Pull request by dantewang**
Hi @adolfopa, this is a pull for MB performance tuning. Could you review it in case we break anything? Thanks!

### CODE REVIEW

**Comment by dantewang** [comment]
cc @tinatian @shuyangzhou

**Comment by dantewang** [comment]
ci:test:messageboards

**Comment by dantewang** [comment]
The failures seems to also happen in this test pull, which has no actual change on MB: https://github.com/yuhai/liferay-portal/pull/140#issuecomment-498969285

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/74187

**Pull request closed without merging**
