### PR TITLE
LPS-103800 Build language autogenerated

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81255. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/1d01b949ba2c~10...1d01b949ba2c)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81452. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/a97052d98414~10...a97052d98414)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/81514. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/c225e433213c~10...c225e433213c)

**Pull request closed without merging**
