### PR TITLE
LPS-102880 test for small image unsupported extension

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
test passed (https://github.com/aliciaGarciaGarcia/liferay-portal/pull/45)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by jpince** [comment]
@austinchiang potential flaky test?

**Comment by austinchiang** [comment]
@jpince @AliciaGarciaGarcia yeah it looks like it's been appearing a lot of pulls recently. It's being worked on in https://issues.liferay.com/browse/LPS-98318

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
It's seems resolved, so I will resend the relevant to test it

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1388. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/7a16142fdf6c~2...7a16142fdf6c)

**Pull request closed without merging**
