### PR TITLE
LPS-68974 Implement PortletDataHandler&ExportImportPortletPreferencesProcessor for KB Display and KB Article portlets

### PR DESCRIPTION
**Pull request by sorin-pop**
Hi Adolfo,

Could you please review these implementations?

Notes:

In processExportPortletPreferences() we used getKBArticleAndAllDescendantKBArticles() in order to fetch the articles to be exported by the portlet. As we see, this method only fetches the main version of every KB article - and this seems consistent to what the WC Display portlet is doing, which is exporting the last approved version of the displayed article. However, please let us know if this is not proper.

Regarding what the KB Display portlet should export if it is set to point to a KB Folder, we eventually decided to only export that folder, without its contents and subfolders, because:

potentially there could be many many subfolders and articles (and sub-articles) under a folder, which would result in the export of a KB Display portlet to run for a long time and export a lot of entities with it, which ultimately doesn't really seem to be what we want to happen when we export a KB Display portlet.
we noticed that this issue is similarly handled when exporting a DL portlets
Cc: @moltam89

Thanks.

### CODE REVIEW

**Comment by moltam89** [comment]
ci:retest

**Comment by moltam89** [comment]
Hi @adolfopa ,

I can't see the connection between the fix and the failing tests, could you please review it?

Thanks,
Tamás

**Comment by adolfopa** [comment]
Reopening this to check errors.

**Comment by adolfopa** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
@moltam89 See https://testray.liferay.com/reports/production/logs/test-1-5/1485268495714/test-portal-acceptance-pullrequest(master)/933/functional-tomcat80-mysql56-jdk8/25/0/jenkins-console.txt.gz

There's a NullPointerException in KBArticlePortletDataHandler (line 62). The thing is that the portletPreferences can be null (see GroupLocalServiceImpl, line 3521), so you need to check that before doing anything.

After reviewing this, I'll send you a pull with the changes for you to take a look.

Thanks!

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sorin-pop/liferay-portal/pull/4. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/d10338b~1...d10338b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/sorin-pop/liferay-portal/pull/5. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/f87b5eb~2...f87b5eb) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
