### PR TITLE
LPS-111773 test to check content reviewer

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1412. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/a5c74cddd4a3~1...a5c74cddd4a3)

**Comment by adolfopa** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1414. [See changes here.](https://github.com/adolfopa/liferay-portal/compare/2d0a97b6cfa5~1...2d0a97b6cfa5)

**Pull request closed without merging**
